### ISSUE TITLE
MCMC for models

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3sim#116]
Just thinking ahead and thought that some people might want to run MCMC on some models, in particular data-moderate ones if we got that working with ss3sim. It would probably be infeasible to run a full Bayesian simulation study with complex models, but might be doable for simpler ones.

I envision running all the models to get MLEs and then having an external function that loops through and runs all models for a set of MCMC parameters (number out, thinning rate, etc.). I already have some functions that would accomplish this, it would just be a matter of linking them in to ss3sim.

**Comment by seananderson** [comment]
I think this is a great idea, but we're unlikely to get to it sometime soon. I'm going to mark this closed (along with some other enhancement issues) to clean up the issue tracker, but we can always find them in the closed issues and implement them later.
