### ISSUE TITLE
Expand on visualizing results and checking convergence

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3sim#123]
We should add a section to the vignette showing how to use ggplot and other tools to quickly explore output to do things like: verify the models are working, explore convergence, show OM trends. I have a bunch of code already developed with manipulate in RStudio that could be really useful for quick analyses, especially for the scalar quantities. I'll volunteer to work this up at some point...

**Comment by kellijohnson-NOAA** [comment]
Some of this was completed in e4ef5f44e3d6d88f032428511b8988e956488f93. I am closing this issue as future edits to the vignette will be plenty but are better described in the project board.
