### ISSUE TITLE
Output files for massive simulations

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3sim#128]
When the size of the simulation study is very, very large, it becomes burdensome to use the get_results code b/c they read in the entire output. This may take too long, or simply produce files that are too large. 

In many cases the user may just be interested in a small subset of what get_results extracts. Thus, we should think about whether it is possible to simplify the get_results code or have an alternative that just uses readLines and doesn't need to parse in the entire complex list structure of each run.

**Comment by kellijohnson-NOAA** [comment]
I think it is better to provide too much than provide only what a user is interested in. Moving forward, I think it would be best to work on making `r4ss::SS_output()` faster than providing less results, thereby maintaining a single function rather than multiple functions in each repository.

**Comment by iantaylor-NOAA** [comment]
This makes sense to me and it would have a big benefit outside of ss3sim.

**Comment by chantelwetzel-noaa** [comment]
There is now a ss_summary.sso file created by SS which has most, if not all, of the outputs one would want to save for a simulation.  This file is much smaller than the full Report.sso file which could speed up reading and storing outputs.  Additionally, there is now an option in the starter file to only write out the ss_summary file and skip the full Report file.  We might want to do some speed tests comparing the read time of the output files.

**Comment by kellijohnson-NOAA** [comment]
Thank you @iantaylor-NOAA and @chantelwetzel-noaa for the input. Is there a current function in r4ss that reads in the ss_summary.sso file and, if so, should we also think about moving the SSsummarize function to use this output if it exists to speed up the creation of likelihood profiles? Darn, I just looked and the summary file doesn't have likelihoods by fleet, which kills that idea.

**Comment by iantaylor-NOAA** [comment]
For future reference, `r4ss::SS_read_summary()` (discussed at https://github.com/r4ss/r4ss/issues/194) will read the `ss_summary.sso` file. If it's important to speed up reading of output for likelihood profiles, feel free to post a new r4ss issue, because we could modify the workflow to facilitate that. However, my sense has always been that `SS_output()` always runs much faster than the SS itself and I may want more detail on any step within the profile so that reading only the likelihood values isn't enough.

**Comment by kellijohnson-NOAA** [comment]
Thanks for the function call. I think that both ss3sim and results for likelihood profiles will need more than the summary file and that the speeding up of SS_output(), if it can be done, is the best option, though not something that is pressing.
