### ISSUE TITLE
Sinking output to cleanup the console

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3sim#152]
So I think we're all pretty sick of seeing:

```
Error -- base = 0 in function prevariable& pow(const prevariable& v1, CGNU_DOUBLE u)
Error trying to open data input file ss3_24~2.dat
```
Fly by on the console. Would it be possible (easy?) to sink the ss3 output to a file while leaving the helpful ss3sim messages/warnings/errors to print to the console? We could sink to a file in a scenario or iteration folder for debugging purposes. But for the most part we don't need to see all that output and any relevant output might be quickly buried in the stream.  I could see how this would get tricky when running in parallel since the console is getting output from multiple runs simultaneously.

**Comment by kellijohnson** [comment]
Added a function https://github.com/ss3sim/ss3models/blob/package/R/make_forecast.R that creates a forecast file for use in ss3sim with commit ss3sim/ss3models@a237ce237881a1dcb05c9c5f1a23756daa5a1a0. Tested it with an OM and it worked fine. Using a template forecast file removes some the potential for error messages in the console. @Kotkot could you run the function once and make sure it generates a sensible forecast file before I close this issue.

**Comment by kellijohnson** [comment]
I turned off some output from the bias correction runs (b90b88d1237028d25059d543ce07e82ff0f0b2c5) which was generated from reading in Report.sso, it helps minimize the amount of text on the screen.
