### ISSUE TITLE
Clean up sampling function roxygen2 templates

### ISSUE THREAD

**Issue by seananderson** [ss3sim/ss3sim#177]
Some of the newer sampling functions, which use the original sampling function template documentation (in `man-roxgygen`) include arguments that don't exist in the newer sampling functions. I guess we'll need to break out the arguments from those templates a bit more and maybe hand document a couple of them.

`R CMD check:`
```
Documented arguments not in \usage in documentation object 'sample_calcomp':
  ‘infile’ ‘Nsamp’ ‘cpar’

Documented arguments not in \usage in documentation object 'sample_mlacomp':
  ‘infile’ ‘cpar’
```

**Comment by kellijohnson** [comment]
Done between commits c143a243c87cd1e91a9e46776550c4751e2e5ffd and 154add4b0da54af23ed5adc131deea706b41c89b. I had to partition some of the templates b/c they were not used in all functions.

**Comment by seananderson** [comment]
Thank you Kelli!
