### ISSUE TITLE
Remaining tasks for change_data()

### ISSUE THREAD

**Issue by seananderson** [ss3sim/ss3sim#195]
- [x] Write `change_pop_bin()` and integrate it in `change_data()`
- [x] Implement changing internal length and age bins in `change_data()`
- [x] Run `clean_data()` before calling `change_data()`
- [x] Integrate the code from `change_lcomp_constant()` and `change_tail_compression()` into `change_data()` (or just call them from in that function); clean out `ss3sim_base()` as needed
- [x] Add case argument passing for `change_data()` instead of how they are coded as arguments in `ss3sim_base()` right now. This case will include population bins, internal length and age bins, length-comp constant, and tail compression.

**Comment by seananderson** [comment]
I just spent some time working on this and I think I've done everything listed above over in the [internal-bins](https://github.com/ss3sim/ss3sim/tree/internal-bins) branch. I also did a bunch of tidying up in general as I went.

There's a test at the bottom of `tests/testthat/test-run-ss3sim.R` that exercises most of the new options and seems to work. The final output OM and EM `.dat` file look right to me, at least. But, I could very well be missing something. Could someone else run the code below, inspect the `.dat` files, and confirm?

You can run this code to check (make sure you're working in the `internal-bins` Git branch first).

```R
load_all()
d <- system.file("extdata", package = "ss3sim")
om <- paste0(d, "/models/cod-om")
em <- paste0(d, "/models/cod-em")
case_folder <- paste0(d, "/cases")
run_ss3sim(iterations = 1, scenarios = "D0-E0-F0-B0-cod",
    case_folder = case_folder, om_dir = om, em_dir = em, ss_mode = "optimized",
    case_files = list(F = "F", D = c("index", "lcomp", "agecomp"), E = "E", B = "data"))
```

We're looking for a data file based on these arguments and the cod model:

`data0-cod.txt`
```
age_bins; NULL
len_bins; seq(20, 155, 3)
pop_binwidth; 2
pop_minimum_size; 8
pop_maximum_size; 202
lcomp_constant; 0.02
tail_compression; 0.05
```

`lcomp0-cod.txt`
```
Nsamp; list(100)
fleets; 1
years; list(1938:2012)
cpar; 2
```

`index0-cod.txt`
```
fleets; 3
years; list(c(seq(1938,1948,by=10), seq(1958, 1983, by=5), seq(1984,2012)))                   
sds_obs; list(.4)
```

`agecomp0-cod.txt`

all `NULL`s

**Comment by kellijohnson** [comment]
I can run the above example on my computer and the dat file looks appropriate. Though I have not tested it with other scenarios.

**Comment by colemonnahan** [comment]
@seananderson  I'll have a look at this tomorrow. I'm not doing any `ss3sim` work Mon/Tues to focus on my general exam.

**Comment by colemonnahan** [comment]
Hi Sean,

Would you mind merging that branch into master? Or pulling changes from master into it? I'm fixing little bugs that need to be in there to more thoroughly test this functionality.

**Comment by colemonnahan** [comment]
I've done some testing and this seems to be working great. Closing.
