### ISSUE TITLE
Remove E as a required case

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3sim#200]
Currently we have to pass E0 to get the simulation to run. As far as I can tell this is unecessary, and we can simply pass a default of NULL to tell `change_e` to do nothing, similar to how the `sample_*` functions are handled. Is this possible @kellijohnson?

**Comment by seananderson** [comment]
This doesn't necessarily need to be dealt with inside `change_e`. We can also just not call `change_e` within `ss3sim_base` if the arguments are NULL (in fact, maybe we already do that?). The only other thing that makes it 'default' is that it's contained in the default argument list in `run_ss3sim`. While we're at it, I suggest we remove retrospective from the defaults.

**Comment by seananderson** [comment]
Since this would require a little search and replace across a bunch of function examples and the vignette, is this how we would want to leave the defaults? I guess we'd just have to strip out the `R0` and `E0` from a bunch of example model runs that don't use these and add R and E to the `case_files` argument where we do use them.

```R
case_files = list(M = "M", F = "F", D = c("index", "lcomp", "agecomp"))
```

**Comment by colemonnahan** [comment]
Agree with you on the approach of ignoring `change_e` if NULL is passed to base. 

I think only F and D should be required. I doubt any of our examples use E, and definitely not R, so that shouldn't be too bad. But we'll find out I guess.

**Comment by kellijohnson** [comment]
I agree with F and D. A great step forward for the package imo.

On Tue, Feb 10, 2015 at 12:37 PM, Cole Monnahan <notifications@github.com>
wrote:

> Agree with you on the approach of ignoring change_e if NULL is passed to
> base.
>
> I think only F and D should be required. I doubt any of our examples use
> E, and definitely not R, so that shouldn't be too bad. But we'll find out I
> guess.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ss3sim/ss3sim/issues/200#issuecomment-73778719>.
>



-- 
Kelli Faye Johnson
kellifayejohnson@gmail.com

**Comment by kellijohnson** [comment]
@seananderson can you handle this one I do not really feel comfortable making the changes as I don't know the internal workings of ss3sim as well as you do?

**Comment by seananderson** [comment]
Sure, I can do this.

**Comment by seananderson** [comment]
I'm a bit late mentioning this, but I did remove all default cases except D and F with this commit:
https://github.com/ss3sim/ss3sim/commit/3bd801a7a829f5e6e661835796d7e2b2d31ee3df

This means you will have to specify the `case_files` list if you have any other cases. This includes old code that usually had M, R, and E cases that often didn't do anything.

Alternatively we could have a long default `case_files` list but not require the user to specify all the elements of the list. That would probably be the more elegant solution but I'm not sure off the top of my head if that would break some other part of the package. Might revisit this in the future.

**Comment by colemonnahan** [comment]
I vote to break backwards compatibility and keep the user interface as simple as possible moving forward.

**Comment by seananderson** [comment]
I'm fine with breaking backwards compatibility, but I could see it being
simpler if we just had a long case argument list that covers everything and
then the user never has to specify it. But I'm not going to worry about
this now.
