### ISSUE TITLE
EM re-binning of conditional age-at-length data

### ISSUE THREAD

**Issue by seananderson** [ss3sim/ss3sim#201]
I think I have dynamic re-binning of the conditional age-at-length data working. The meat of the new code is here: 

https://github.com/ss3sim/ss3sim/blob/cal-rebin/R/change_em_binning.r#L167-L212

The strange structure of the CAL data meant that following the format Kot used for the length re-binning was going to be a huge pain, so I pulled out dplyr.

This seems to work with the simple example I coded up, but I'm probably overlooking all sorts of edge cases right now. I'm also not sure how much I can rely on the id column names being the same every time. Maybe it's OK here since the data file will have always gone through change_data first?

Output from `dev_example("change_em_binning")`:
```
> f <- system.file("extdata", "models", "cod-om", "codOM.dat", package = "ss3sim")
> d <- r4ss::SS_readdat(f)
> # Add catch at length data (and simplify the bin structure for this example)
> datfile <- ss3sim::change_data(d, outfile = NULL, write_file = FALSE,
+   types = c("len", "age", "cal"), fleets = 1, years = seq(2000, 2002),
+   age_bins = 1:3, len_bins = 4:8)
> datfile$agecomp
     Yr Seas Flt Gender Part AgeErr Lbin_lo Lbin_hi Nsamp a1 a2 a3
1  2000    1   1      0    0      1      -1      -1     3  1  1  1
2  2001    1   1      0    0      1      -1      -1     3  1  1  1
3  2002    1   1      0    0      1      -1      -1     3  1  1  1
4  2000    1   1      0    0      1       1       1     3  1  1  1
5  2000    1   1      0    0      1       2       2     3  1  1  1
6  2000    1   1      0    0      1       3       3     3  1  1  1
7  2000    1   1      0    0      1       4       4     3  1  1  1
8  2000    1   1      0    0      1       5       5     3  1  1  1
9  2001    1   1      0    0      1       1       1     3  1  1  1
10 2001    1   1      0    0      1       2       2     3  1  1  1
11 2001    1   1      0    0      1       3       3     3  1  1  1
12 2001    1   1      0    0      1       4       4     3  1  1  1
13 2001    1   1      0    0      1       5       5     3  1  1  1
14 2002    1   1      0    0      1       1       1     3  1  1  1
15 2002    1   1      0    0      1       2       2     3  1  1  1
16 2002    1   1      0    0      1       3       3     3  1  1  1
17 2002    1   1      0    0      1       4       4     3  1  1  1
18 2002    1   1      0    0      1       5       5     3  1  1  1
> newdat <- change_em_binning(datfile, file_out = NULL, bin_vector = c(4, 6, 8),
+   lbin_method = 1, rebin_cal = TRUE, write_file = FALSE)
> newdat$agecomp
     Yr Seas Flt Gender Part AgeErr Lbin_lo Lbin_hi Nsamp a1 a2 a3
1  2000    1   1      0    0      1      -1      -1     3  1  1  1
2  2001    1   1      0    0      1      -1      -1     3  1  1  1
3  2002    1   1      0    0      1      -1      -1     3  1  1  1
4  2000    1   1      0    0      1       1       1     3  2  2  2
5  2000    1   1      0    0      1       2       2     3  2  2  2
6  2000    1   1      0    0      1       3       3     3  1  1  1
7  2001    1   1      0    0      1       1       1     3  2  2  2
8  2001    1   1      0    0      1       2       2     3  2  2  2
9  2001    1   1      0    0      1       3       3     3  1  1  1
10 2002    1   1      0    0      1       1       1     3  2  2  2
11 2002    1   1      0    0      1       2       2     3  2  2  2
12 2002    1   1      0    0      1       3       3     3  1  1  1
```

**Comment by seananderson** [comment]
I added a larger example. Can someone more versed in SS3 data file manipulation check this out and make sure I'm not doing something silly?

```R
install_github("ss3sim/ss3sim@cal-rebin")
library("ss3sim")
f <- system.file("extdata", "models", "cod-om", "codOM.dat", package = "ss3sim")
d <- r4ss::SS_readdat(f)
olddat <- change_data(d, outfile = NULL, write_file = FALSE,
 types = c("len", "age", "cal"), fleets = 1, years = seq(2000, 2005),
 age_bins = seq(1, 5), len_bins = round(seq(20, 30, length.out = 13), 1))
olddat$lbin_vector
head(olddat$lencomp)
head(olddat$agecomp)
newdat <- change_em_binning(olddat, file_out = NULL, bin_vector = seq(20, 30, 2),
 lbin_method = 1, rebin_cal = TRUE, write_file = FALSE)
newdat$lbin_vector
head(newdat$lencomp)
newdat$agecomp
```

Output:

```
> olddat <- change_data(d, outfile = NULL, write_file = FALSE,
+     types = c("len", "age", "cal"), fleets = 1, years = seq(2000, 2005),
+     age_bins = seq(1, 5), len_bins = round(seq(20, 30, length.out = 13), 1))
> olddat$lbin_vector
 [1] 20.0 20.8 21.7 22.5 23.3 24.2 25.0 25.8 26.7 27.5 28.3 29.2 30.0
> head(olddat$lencomp)
    Yr Seas Flt Gender Part Nsamp l20 l20.8 l21.7 l22.5 l23.3 l24.2 l25 l25.8 l26.7 l27.5
1 2000    1   1      0    0    10   1     1     1     1     1     1   1     1     1     1
2 2001    1   1      0    0    10   1     1     1     1     1     1   1     1     1     1
3 2002    1   1      0    0    10   1     1     1     1     1     1   1     1     1     1
4 2003    1   1      0    0    10   1     1     1     1     1     1   1     1     1     1
5 2004    1   1      0    0    10   1     1     1     1     1     1   1     1     1     1
6 2005    1   1      0    0    10   1     1     1     1     1     1   1     1     1     1
  l28.3 l29.2 l30
1     1     1   1
2     1     1   1
3     1     1   1
4     1     1   1
5     1     1   1
6     1     1   1
> head(olddat$agecomp)
    Yr Seas Flt Gender Part AgeErr Lbin_lo Lbin_hi Nsamp a1 a2 a3 a4 a5
1 2000    1   1      0    0      1      -1      -1     5  1  1  1  1  1
2 2001    1   1      0    0      1      -1      -1     5  1  1  1  1  1
3 2002    1   1      0    0      1      -1      -1     5  1  1  1  1  1
4 2003    1   1      0    0      1      -1      -1     5  1  1  1  1  1
5 2004    1   1      0    0      1      -1      -1     5  1  1  1  1  1
6 2005    1   1      0    0      1      -1      -1     5  1  1  1  1  1
> newdat <- change_em_binning(olddat, file_out = NULL, bin_vector = seq(20, 30, 2),
+     lbin_method = 1, rebin_cal = TRUE, write_file = FALSE)
> newdat$lbin_vector
[1] 20 22 24 26 28 30
> head(newdat$lencomp)
    Yr Seas Flt Gender Part Nsamp l20 l22 l24 l26 l28 l30
1 2000    1   1      0    0    10   3   2   3   2   2   1
2 2001    1   1      0    0    10   3   2   3   2   2   1
3 2002    1   1      0    0    10   3   2   3   2   2   1
4 2003    1   1      0    0    10   3   2   3   2   2   1
5 2004    1   1      0    0    10   3   2   3   2   2   1
6 2005    1   1      0    0    10   3   2   3   2   2   1
> newdat$agecomp
     Yr Seas Flt Gender Part AgeErr Lbin_lo Lbin_hi Nsamp a1 a2 a3 a4 a5
1  2000    1   1      0    0      1      -1      -1     5  1  1  1  1  1
2  2001    1   1      0    0      1      -1      -1     5  1  1  1  1  1
3  2002    1   1      0    0      1      -1      -1     5  1  1  1  1  1
4  2003    1   1      0    0      1      -1      -1     5  1  1  1  1  1
5  2004    1   1      0    0      1      -1      -1     5  1  1  1  1  1
6  2005    1   1      0    0      1      -1      -1     5  1  1  1  1  1
7  2000    1   1      0    0      1       1       1     5  3  3  3  3  3
8  2000    1   1      0    0      1       2       2     5  2  2  2  2  2
9  2000    1   1      0    0      1       3       3     5  3  3  3  3  3
10 2000    1   1      0    0      1       4       4     5  2  2  2  2  2
11 2000    1   1      0    0      1       5       5     5  2  2  2  2  2
12 2000    1   1      0    0      1       6       6     5  1  1  1  1  1
13 2001    1   1      0    0      1       1       1     5  3  3  3  3  3
14 2001    1   1      0    0      1       2       2     5  2  2  2  2  2
15 2001    1   1      0    0      1       3       3     5  3  3  3  3  3
16 2001    1   1      0    0      1       4       4     5  2  2  2  2  2
17 2001    1   1      0    0      1       5       5     5  2  2  2  2  2
18 2001    1   1      0    0      1       6       6     5  1  1  1  1  1
19 2002    1   1      0    0      1       1       1     5  3  3  3  3  3
20 2002    1   1      0    0      1       2       2     5  2  2  2  2  2
21 2002    1   1      0    0      1       3       3     5  3  3  3  3  3
22 2002    1   1      0    0      1       4       4     5  2  2  2  2  2
23 2002    1   1      0    0      1       5       5     5  2  2  2  2  2
24 2002    1   1      0    0      1       6       6     5  1  1  1  1  1
25 2003    1   1      0    0      1       1       1     5  3  3  3  3  3
26 2003    1   1      0    0      1       2       2     5  2  2  2  2  2
27 2003    1   1      0    0      1       3       3     5  3  3  3  3  3
28 2003    1   1      0    0      1       4       4     5  2  2  2  2  2
29 2003    1   1      0    0      1       5       5     5  2  2  2  2  2
30 2003    1   1      0    0      1       6       6     5  1  1  1  1  1
31 2004    1   1      0    0      1       1       1     5  3  3  3  3  3
32 2004    1   1      0    0      1       2       2     5  2  2  2  2  2
33 2004    1   1      0    0      1       3       3     5  3  3  3  3  3
34 2004    1   1      0    0      1       4       4     5  2  2  2  2  2
35 2004    1   1      0    0      1       5       5     5  2  2  2  2  2
36 2004    1   1      0    0      1       6       6     5  1  1  1  1  1
37 2005    1   1      0    0      1       1       1     5  3  3  3  3  3
38 2005    1   1      0    0      1       2       2     5  2  2  2  2  2
39 2005    1   1      0    0      1       3       3     5  3  3  3  3  3
40 2005    1   1      0    0      1       4       4     5  2  2  2  2  2
41 2005    1   1      0    0      1       5       5     5  2  2  2  2  2
42 2005    1   1      0    0      1       6       6     5  1  1  1  1  1
```

**Comment by kellijohnson** [comment]
At a quick glance two items:
  * make sure the data bin width specified is divisible by the 
population length bin width because the model will fail otherwise (e.g., 
population length bin width of 2 must correspond with only even data bin 
widths)
  * what happens when a user specifies more bins than what was used in 
the original model rather than less?
  * does it  matter if fish are in real numbers or if they are specified 
in proportions?

I will look at the lbin method part in a minute.

**Comment by taylori** [comment]
I agree with Kot's point about divisibility.
Real numbers and proportions both work--I prefer real numbers because the
files are more readable, but it's a personal choice.

The choice of lbin_method = 1 has the Lbin_lo Lbin_hi columns for the
conditional age-at-length data referring to the index of the associated
population length bin (as opposed to 2. the index of the data length bin,
or 3. the actual length in cm). For real data, I like using option 3 in cm
because I it allows adding additional bins without revising your data, but
I don't know enough about the rebinning project to know what is the best
option for ss3sim. If you plan to rebin the data length bins but not the
population length bins, then options 1 and 3 would be better than 2 because
you wouldn't have to renumber the conditional ages. But if you're
aggregating length bins and also conditional age data into the new bins,
then any of the options should work as long as you get the code right.

-Ian

**Comment by kellijohnson** [comment]
more things, maybe:
 * need something for ```if (lbin_method == 2) {``` if there would ever be a model that started as a method 1 and you need to add the 3 additional inputs of binwidth, minimum size, and maximum size;
 * cal data can be defined using ```Lbin_lo``` or ```Lbin_hi```, where you only check for the later, or at least I think it can when ```L_binlo == 1```;
 * I leave it to the binning group to check the part of the code where it says magic happens here as I am not familiar with dplyr, sorry as this was the actual issue.

**Comment by seananderson** [comment]
Thanks for the feedback on this. I was confused about the `lbin_method` thing until Kot pointed out that there are two kinds of similar variables and the `lbin_method` used in the current function is the other one. If I understand this correctly, it's `Lbin_method` as returned by r4ss that is relevant to the conditional age-at-length data. I believe the code I wrote already works with `Lbin_method = 2` and it's probably simplest just to set up our .dat files that way (or make sure that `change_data()` is doing that).

I've added some checks in these two commits that cover many of the above potential issues:
https://github.com/ss3sim/ss3sim/commit/93eb1d6570f05e6ef4963626dad126567c0fec62
https://github.com/ss3sim/ss3sim/commit/1002d437a1738a7d0d2c1ec9078e27c8bcdb9030

**Comment by colemonnahan** [comment]
I vote that we force the users to explicitly define their length bins and age bins using method 2.

**Comment by colemonnahan** [comment]
I'm having a look at this now (finally!). 

I originally used `Lbin_method=2` because that was how the original data file I happened to use was set up. In other words, it was by chance. Now that I think about it, I do think we should switch to `Lbin_method=3` so that we can see the actual bins. I think it would be more clear this way, especially when we start doing uneven bins. If we go this route the only thing needing to be changed is in the `make_dummy_data_calcomp` function. If no one objects I will move in that direction.

Sean: I modified your example to have original bins of length 1cm. This is a more realistic scenario since the "old" data file represents measured fish at a natural length in their unprocessed form. I don't think anyone measures them to anything other than 1cm, with the possible except of .5cm. So we can focus on those two bins in the original data file.

The SS3 manual says that the length bins given are: 
> Vector containing lower edge of length bins. The last length bin will have same width as next lower bin

So in the case where our new bins are L20, L22, L24, ... L30, the bin 'L20' would contain all fish between 20 and 22cm, which would be l20 and l21 of the original bins, but NOT l22 since that includes fish that are greater than 22cm. When I run the `change_em_binning` function it gives this for lengths (and calcomps but not shown here):

````
l20	l21	l22	l23	l24	l25	l26	l27	l28	l29	l30
1	1	1	1	1	1	1	1	1	1	1
````
becomes
````
l20	l22	l24	l26	l28	l30
3	2	3	2	2	1
````
But shouldn't that be
````
l20	l22	l24	l26	l28	l30
2	2	2	2	2	1
````
Where L20=l20+l21; L22=l22+l23, etc., and then L30 is all greater than or equal to it.

@Kotkot  and @seananderson what are your thoughts? My impression is that the logic should be this: Assume new bin N with length X cm. Let old bin B1 be the largest bin >=X. Let old bin B2 be the largest bin that is strictly less than the next new bin N+1. Sum across bins B1 to B2. Right now we're not handling the boundaries in this way.

**Comment by seananderson** [comment]
Can you provide a working example of what you describe above, @colemonnahan ? To me it looks like the binning is working as you describe it should. I'm just using `findInterval()` to do the re-binning, which should work as you describe, I believe.

```R
# load the cal-rebin branch of the package...

f <- system.file("extdata", "models", "cod-om", "codOM.dat", package = "ss3sim")
d <- r4ss::SS_readdat(f)
d$Lbin_method <- 2
> olddat <- change_data(d, outfile = NULL, write_file = FALSE,
    types = c("len", "age", "cal"), fleets = 1, years = seq(2000, 2002),
    age_bins = 1:3, len_bins = 4:8)
> olddat$agecomp
     Yr Seas Flt Gender Part AgeErr Lbin_lo Lbin_hi Nsamp a1 a2 a3
1  2000    1   1      0    0      1      -1      -1     3  1  1  1
2  2001    1   1      0    0      1      -1      -1     3  1  1  1
3  2002    1   1      0    0      1      -1      -1     3  1  1  1
4  2000    1   1      0    0      1       1       1     3  1  1  1
5  2000    1   1      0    0      1       2       2     3  1  1  1
6  2000    1   1      0    0      1       3       3     3  1  1  1
7  2000    1   1      0    0      1       4       4     3  1  1  1
8  2000    1   1      0    0      1       5       5     3  1  1  1
9  2001    1   1      0    0      1       1       1     3  1  1  1
10 2001    1   1      0    0      1       2       2     3  1  1  1
11 2001    1   1      0    0      1       3       3     3  1  1  1
12 2001    1   1      0    0      1       4       4     3  1  1  1
13 2001    1   1      0    0      1       5       5     3  1  1  1
14 2002    1   1      0    0      1       1       1     3  1  1  1
15 2002    1   1      0    0      1       2       2     3  1  1  1
16 2002    1   1      0    0      1       3       3     3  1  1  1
17 2002    1   1      0    0      1       4       4     3  1  1  1
18 2002    1   1      0    0      1       5       5     3  1  1  1
> newdat <- change_em_binning(olddat, file_out = NULL, bin_vector = c(4, 6, 8),
    lbin_method = 1, rebin_cal = TRUE, write_file = FALSE)
> newdat$agecomp
     Yr Seas Flt Gender Part AgeErr Lbin_lo Lbin_hi Nsamp a1 a2 a3
1  2000    1   1      0    0      1      -1      -1     3  1  1  1
2  2001    1   1      0    0      1      -1      -1     3  1  1  1
3  2002    1   1      0    0      1      -1      -1     3  1  1  1
4  2000    1   1      0    0      1       1       1     3  2  2  2
5  2000    1   1      0    0      1       2       2     3  2  2  2
6  2000    1   1      0    0      1       3       3     3  1  1  1
7  2001    1   1      0    0      1       1       1     3  2  2  2
8  2001    1   1      0    0      1       2       2     3  2  2  2
9  2001    1   1      0    0      1       3       3     3  1  1  1
10 2002    1   1      0    0      1       1       1     3  2  2  2
11 2002    1   1      0    0      1       2       2     3  2  2  2
12 2002    1   1      0    0      1       3       3     3  1  1  1
> head(newdat$lencomp)
    Yr Seas Flt Gender Part Nsamp l4 l6 l8
1 2000    1   1      0    0    10  2  2  1
2 2001    1   1      0    0    10  2  2  1
3 2002    1   1      0    0    10  2  2  1
```

**Comment by seananderson** [comment]
Regarding the other parts of your comments:

> I originally used `Lbin_method=2` because that was how the original data file I happened to use was set up. In other words, it was by chance. Now that I think about it, I do think we should switch to `Lbin_method=3` so that we can see the actual bins. I think it would be more clear this way, especially when we start doing uneven bins. If we go this route the only thing needing to be changed is in the `make_dummy_data_calcomp` function. If no one objects I will move in that direction.

Sure, that's fine. I'll also have to tweak the re-binning script. `make_dummy_data_calcomp` just needs to be changed so that `Lbin_lo` and `Lbin_hi` take on bin values themselves instead of indices, right? If so, I can do that at the same time. Also to confirm, I presume that with `Lbin_method = 3`, `Lbin_lo` represents the lower bin value and `Lbin_hi` represents the upper bin value within each row, right? Just not sure I've seen one of these in the wild to confirm.

> Sean: I modified your example to have original bins of length 1cm. This is a more realistic scenario 

Sounds good (although I don't think your code is pushed yet). I was just showing what the function could do, not necessarily being realistic.

**Comment by seananderson** [comment]
OK, I've tweaked `make_dummy_data_calcomp` and `change_em_binning`. I hope I've interpreting the SS3 manual correctly here on how to specify `Lbin_lo` and `Lbin_hi` for CAL given `Lbin_method = 3`. Let me know if not. I set the upper bin level to -1. Here's some example code that demonstrates both parts (`change_data()` uses `make_dummy_data_calcomp()` internally):

```R
> devtools::load_all()
> devtools::dev_example("change_em_binning")
> # ...
> f <- system.file("extdata", "models", "cod-om", "codOM.dat", package = "ss3sim")
> d <- r4ss::SS_readdat(f)
> d$Lbin_method <- 3 # necessary for CAL rebinning
> 
> # Add catch at length data (and simplify the bin structure for this example)
> olddat <- change_data(d, outfile = NULL, write_file = FALSE,
    types = c("len", "age", "cal"), fleets = 1, years = seq(2000, 2002),
    age_bins = 1:3, len_bins = 4:8)
> olddat$agecomp
     Yr Seas Flt Gender Part AgeErr Lbin_lo Lbin_hi Nsamp a1 a2 a3
1  2000    1   1      0    0      1      -1      -1     3  1  1  1
2  2001    1   1      0    0      1      -1      -1     3  1  1  1
3  2002    1   1      0    0      1      -1      -1     3  1  1  1
4  2000    1   1      0    0      1       4       5     3  1  1  1
5  2000    1   1      0    0      1       5       6     3  1  1  1
6  2000    1   1      0    0      1       6       7     3  1  1  1
7  2000    1   1      0    0      1       7       8     3  1  1  1
8  2000    1   1      0    0      1       8      -1     3  1  1  1
9  2001    1   1      0    0      1       4       5     3  1  1  1
10 2001    1   1      0    0      1       5       6     3  1  1  1
11 2001    1   1      0    0      1       6       7     3  1  1  1
12 2001    1   1      0    0      1       7       8     3  1  1  1
13 2001    1   1      0    0      1       8      -1     3  1  1  1
14 2002    1   1      0    0      1       4       5     3  1  1  1
15 2002    1   1      0    0      1       5       6     3  1  1  1
16 2002    1   1      0    0      1       6       7     3  1  1  1
17 2002    1   1      0    0      1       7       8     3  1  1  1
18 2002    1   1      0    0      1       8      -1     3  1  1  1
> newdat <- change_em_binning(olddat, file_out = NULL, bin_vector = c(4, 6, 8),
    lbin_method = 1, rebin_cal = TRUE, write_file = FALSE)
> newdat$agecomp
     Yr Seas Flt Gender Part AgeErr Lbin_lo Lbin_hi Nsamp a1 a2 a3
1  2000    1   1      0    0      1      -1      -1     3  1  1  1
2  2001    1   1      0    0      1      -1      -1     3  1  1  1
3  2002    1   1      0    0      1      -1      -1     3  1  1  1
4  2000    1   1      0    0      1       4       6     3  2  2  2
5  2000    1   1      0    0      1       6       8     3  2  2  2
6  2000    1   1      0    0      1       8      -1     3  1  1  1
7  2001    1   1      0    0      1       4       6     3  2  2  2
8  2001    1   1      0    0      1       6       8     3  2  2  2
9  2001    1   1      0    0      1       8      -1     3  1  1  1
10 2002    1   1      0    0      1       4       6     3  2  2  2
11 2002    1   1      0    0      1       6       8     3  2  2  2
12 2002    1   1      0    0      1       8      -1     3  1  1  1
```

**Comment by colemonnahan** [comment]
@seananderson this looks great. Yes the only thing to change is in the dummy data. I reran my scenarios from the previous post and got the correct results using your new code -- so I'm not sure what was going on there, probably a dumb mistake on my end. So this approach seems to work with one bug I found:

`findIntervals` returns 0 if the new bin is bigger than any of the old bins. Like this:

````
> findInterval(1:10, c(2,4,6))
 [1] 0 1 1 2 2 3 3 3 3 3
````
So I think we need to counter this by replacing any 0's with 1's. We should also throw a check in there that the new samples sum up to the old ones, ensuring Nsamp is correct.

Sean: If you merge this into master I can test it out inside the package.

**Comment by seananderson** [comment]
OK, with pull request #205 I also:

- enforced that the min and max old and new bins must be the same. We can change that if we want, but that's the simplest and safest place to start from.
- added a check that no length or age samples were lost during the re-binning
- integrated the new functionality into `ss3sim_base`
- merged into master

**Comment by colemonnahan** [comment]
Hi Sean, can I ask you to strip out the `rebin_cal` argument of `change_em_binning`? This function has its own case files to be used across a range of data cases, some with calcomps and some without. So it needs to be able to dynamically handle calcomp data. I suggest just replacing `if(rebin_cal)` with something like `if(nrow(calcomp)==0)`. You already have a check for whether it exists as an error inside, so might as well just use that.

I'd do this myself but at this point don't totally understand your binning code. Make sense why this is needed?

**Comment by seananderson** [comment]
Sure, done with this commit: https://github.com/ss3sim/ss3sim/commit/5b29b3f72d9bd387daf1a874aa51601116e9dd7a
