### ISSUE TITLE
Turning off bootstrapping

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3sim#206]
@Kotkot I noticed that for the yellow model bootstrapping is turned off and I'm getting an error because it can't find the string "#_bootstrap file: 1" used in this function:

https://github.com/ss3sim/ss3sim/blob/master/R/extract_expected_data.r

I suggest we turn off bootstrapping and fix this function so it looks for the end of file some other way. Are there any other instances that will break if we don't have bootstrapped data?

**Comment by colemonnahan** [comment]
In the meantime I turned bootstrapping back on in the yellow model.

**Comment by kellijohnson** [comment]
I will look into the files not being consistent.

Can I change extract_expected_data to use SS_readdat and SS_writedat?

**Comment by colemonnahan** [comment]
I'm OK with that, just use `verbose=FALSE`

**Comment by kellijohnson** [comment]
I ended up using 999, but I cannot check it b/c of the index thing.

**Comment by colemonnahan** [comment]
999 failed for me since it can occur in the data values. More reliable, I think, is the "ENDDATA" string that concludes the expected values section. I updated the `extract_expected_values` function and added some informative errors. It seems to be working nicely for the tests I've done.

**Comment by taylori** [comment]
ENDDATA only occurs at the end of the file, so if you want something robust
to the possibility of including bootstrap files in the future, you could
test for the presence of "#_bootstrap file: 1" which could be used as an
alternative marker to ENDDATA for the end of the expected values if
bootstrap files exist. That would be easy to add someday in the future
should it ever become necessary so I wouldn't worry about it now.
