### ISSUE TITLE
parsing species with "-age" suffix in get_results_all

### ISSUE THREAD

**Issue by peterkuriyama** [ss3sim/ss3sim#209]
@seananderson I installed the package this morning and read in results. I don't *think* the "hake-age" and "yellow-age" species are parsing correctly. I coded a work around, and it's a minor issue.

**Comment by kellijohnson** [comment]
@peterkuriyama can you checkout https://github.com/ss3sim/ss3sim/tree/sppname and see if it does what you want without breaking anything? If it does not break anything, which I don't think it does I can merge it into master.

**Comment by seananderson** [comment]
What was the outcome of this? I remember being confused why there was still an issue. @kellijohnson , did you merge in your branch?

**Comment by kellijohnson** [comment]
Yes we are good to go with commits 16cba7ff625082a40bf18115f7586d515526cb36 and c5c134b8b1f28d5b32073cbf07add67a970b9f66 which allow for hyphens in species names.
