### ISSUE TITLE
Test integrated executable on Windows

### ISSUE THREAD

**Issue by seananderson** [ss3sim/ss3sim#217]
Can someone on a Windows machine test the integration of the SS3 executable in the package? Try temporarily renaming the file `ss3_24o_safe.exe` in your path to anything else and then run:

```R
devtools::install_github("ss3sim/ss3sim", ref = "easy-install")

get_bin() # should give path within package to ss3_24o_safe.exe

d <- system.file("extdata", package = "ss3sim")
om <- paste0(d, "/models/cod-om")
em <- paste0(d, "/models/cod-em")
case_folder <- paste0(d, "/eg-cases")
run_ss3sim(iterations = 1, scenarios = "D0-F0-cod",
  case_folder = case_folder, om_dir = om, em_dir = em)
```

The approach is to look for the binary in the `inst/bin` folder, say from the GitHub package. If that fails, say because it's a CRAN install and we can't include the binaries there, it then looks for the executable in the user's path as before.

This should avoid having to fiddle with executables and paths on fresh installs making the install experience simpler for any new user and especially at workshops. Seems to work on OS X for me.

Branch is here https://github.com/ss3sim/ss3sim/tree/easy-install

**Comment by kellijohnson** [comment]
@seananderson it half worked and half failed :)

when I do `get_bin()` I get: "C:/~/R/R-3.1.2/library/ss3sim/bin/Windows64/ss3_24o_opt.exe"
and when I run the code above it gives me an error:

Running OM for scenario: D0-F0-cod; iteration: 1
Error in ss3sim_base(scenarios = "D0-F0-cod", user_recdevs = NULL, em_dir = "C:/~/R/R-3.1.2/library/ss3sim/extdata/models/cod-em",  : 
  The data.ss_new not created in *first* OM run for D0-F0-cod-1: is something wrong with initial model files?
In addition: Warning message:
running command 'ss3_24o_safe -nohess' had status 127 

If I specify ```ss_mode = "optimized"```` then everything works peachy.

**Comment by kellijohnson** [comment]
Never mind it does not work at all, the only reason the above worked was because I did not change the name of the optimized version that was originally in my path.

**Comment by colemonnahan** [comment]
It seems to work fine for me on Win10, R 3.2.2.
````
> get_bin()
[1] "C:/Users/Cole/Rlibs/ss3sim/bin/Windows64/ss3_24o_opt.exe"
> get_bin('ss3_24o_safe.exe')
[1] "C:/Users/Cole/Rlibs/ss3sim/bin/Windows64/ss3_24o_safe.exe.exe"
>
````
Not sure if that extra .exe on the end makes any difference, but might want to check if the user supplied that.

**Comment by seananderson** [comment]
Thanks Cole. I fixed some things last night and it works for Kelli now too. I just removed the `.exe` appending. Kelli thinks that isn't needed and I don't think it was included in past calls.

I'm back to the erroneous warning `Error trying to open data input file ...` which may or may not be easy to fix, but I think having the executables automatically included is more important.

**Comment by colemonnahan** [comment]
That is an ADMB issue, which we discussed in issue https://github.com/ss3sim/ss3sim/issues/152. Leave it be..

Glad to hear that's working and I think a nice step forward.
