### ISSUE TITLE
The number of years in the models

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3sim#218]
In exploring a longer burn in for the yellow model I noticed a few things that should be considered.
1. The lengths of the models are probably not long enough to get a equilibrated catch when using `profile_fmsy` to create the F case files. The catch curves for yellow-long are different than for yellow, where the only difference is the length of the model. You can see in [this plot](https://github.com/ss3sim/ss3models/blob/master/extra/plots/catch_curves.png) that the curve for yellow-long is always lower. This is because we start at unfished and it doesn't have enough time to equilibrate so it is always high. We are therefore consistently overestimating FMSY, although probably less so for the other models due to the life history of yellow-eye being so long.
2. Similarly, I checked whether the burn in was sufficient for the other models and it does appear so for cod and flatfish, but we should check that. See [this plot](https://github.com/ss3sim/binning/blob/master/plots/burn_in_test2.png) which shows the standard deviation of SSB in the OM under no fishing. It starts at equilibrium so the sd is zero, then increases as the recruitment deviations propagate through the population. 
3. It is **not** trivial to change the years in a model. One needs to update the OM, EM, and reproduce F case files. The function `change_year` gets us pretty close but this is not ready to be done dynamically, and I doubt a new user would be able to accomplish this process. Kelli and I worked through some of the bugs, but it still requires a pretty in-depth knowledge of the how package works.

I suggest we revisit this issue if the package picks up in usage. The previous overhaul (creating the ss3models repo, standardizing bounds, etc.) of the models was a big step forward. I suggest another is warranted at some future point.

**Comment by kellijohnson** [comment]
Just push an overhaul to `change_year`. @colemonnahan could you check to see if it fixed the issues you were dealing with regarding the yelloweye model?

**Comment by kellijohnson-NOAA** [comment]
Wrote a check in profile_fmsy (23c395f) to catch models that aren't being ran for enough years to calculate F_MSY based on the CV of the catches in the terminal year of the model if fishing at a constant rate b/c they should level off over time.
