### ISSUE TITLE
Standardize use of replicate and iteration

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3sim#219]
We're really inconsistent about the use of this term. I think we should exclusively use 'replicate' but at least we should be consistent. For instance `run_ss3sim` uses iteration but some of the result files have replicate. 

IMO: Iterations apply to the solver, replicates apply to different process errors.

Something to add to the list when we go through the documentation next time.

**Comment by kellijohnson** [comment]
Jim Ianelli suggested the use of replicate, or simulation, rather than iteration, for reasons that escape me.

**Comment by kellijohnson-NOAA** [comment]
ca63340a0ebd1b4aef9bbd855af0adc0ffa19044 completes this issue by changing from replicate to iteration, which resulted in less changes than doing the reverse.
