### ISSUE TITLE
Error in system call with spaces in path on Windows

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3sim#222]
In the system call in `run_ss3model` to run the model, an error occurs if there is a space in the path name for the executable. By default on Windows it'll be in '../Program Files' so it needs to be robust to this.

Kelli tried doing `paste(shQuotes(bin, " "))` instead of `paste(bin, " ")`. See line 84 of `run_ss3model.r`.

@seananderson As far as we can tell this only occurs in this function. Can you think of anywhere else we need to be careful about this? It's an easy fix but you would know best if there are other matters we should be aware of.

**Comment by seananderson** [comment]
I think this commit https://github.com/ss3sim/ss3sim/commit/23dfdaa126023866aae3f562ea6952b17481cc54 by @kellijohnson should work everywhere.
