### ISSUE TITLE
Incrementing the package version

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3sim#223]
@seananderson Can you please increment the package version? It would be really helpful for the workshop to be able to test to see how old an installed library is.

Ideally we'd be able to see what branch/commit the package was built from, but I didn't see an option for that online. Is that possible?

**Comment by seananderson** [comment]
People can install from a specific commit. But I don't think we can easily tell which commit was installed from the besides looking at the package version.

We can start bumping the development portion of the version number with commits, if that is helpful.

E.g. https://github.com/ss3sim/ss3sim/commit/af195ce8cf8afc5d989992182b00b5d995f486fc

The plan is to jump to 0.9.0 when we submit to CRAN.

**Comment by colemonnahan** [comment]
I doubt we want to update the version with each commit. Maybe you're right that specifying a commit when installing is the best.

I think with the other changes this shouldn't be an issue, as we'll have everyone up-to-date for the workshop. But moving forward we should probably specify commits when running real simulations so the code is reproducible.
