### ISSUE TITLE
Dependencies stringi and Rcurl failed to install

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3sim#225]
@seananderson When we had people install with 
`devtools::install_github('ss3sim/ss3sim', dependencies = TRUE,
  build_vignettes = TRUE)`

It failed to install the `stringi` and `Rcurl` packages. We couldn't see any reason in the DESSCRIPTION file why this would be. Thoughts?

**Comment by seananderson** [comment]
Those are dependencies of dependencies. Could be this: http://stackoverflow.com/questions/31038636/package-stringi-does-not-work-after-updating-to-r3-2-1

And then failing for people who don't have the requirements to build these packages from source.

Were people still able to work through the code?

**Comment by colemonnahan** [comment]
I think we fixed this issue by forcing an install of devtools.

The trial run was a total failure. 5/6 people had installation issues so we didn't even get beyond that. Hence the flurry of fixes and issues...
