### ISSUE TITLE
Apparent typo in `change_data.r` function 

### ISSUE THREAD

**Issue by awhitten** [ss3sim/ss3sim#227]
Lines 335 and 336 in `change_data.r` seem to have a typo. I got this error and it had me confused for a while. I later worked out that `Nfleet` should probably (?) be `Nsurvey`, unless I'm misunderstanding something about the setup here. The code currently checks for the number of surveys, and then reports back on the number of fleets in the error message.

Currently code is: 
`if` (!identical(x$Nsurveys, 2))`
    `stop("Nfleet in the SS3 data file must be set to 2.")`

Suggest change to:
`if` (!identical(x$Nsurveys, 2))`
    `stop("Nsurvey in the SS3 data file must be set to 2.")`

Tagging @colemonnahan @seananderson and @kellijohnson at the suggestion of Cole. :+1:

**Comment by colemonnahan** [comment]
@awhitten Thanks for posting this. 

I had a look at this code and it's clearly a typo in the error message ( should be survey). But I'm not sure why that line is even in there. Can't the user have as many surveys as they want? Does anyone else remember why this was put in?

**Comment by kellijohnson** [comment]
I am not sure if we have actually ever tested the code to work with more than one fishery and one survey. Theoretically it is possible, but my guess is there will be a few bugs somewhere. Also, @seananderson added the code referenced above with 63664cbf9caddfec628cdb146048af7bd099bd78

**Comment by colemonnahan** [comment]
I think the sampling functions would work, but yeah it'd be a small miracle if nothing broke. For some reason all of our models are setup with a dummy survey. I can't remember why?

**Comment by kellijohnson** [comment]
was not that to use CPUE data if we wanted to?

**Comment by colemonnahan** [comment]
But can't we just use the fishery fleet for that?

**Comment by kellijohnson** [comment]
I think in case we wanted a fleet CPUE and a survey CPUE.

**Comment by colemonnahan** [comment]
Right, which is why we only need two fleets: one for the fishery and one
survey. The third CPUE fleet seems redundant to me.

**Comment by seananderson** [comment]
Thanks for finding that, @awhitten. Sorry for the copy-paste error. I've fixed the typo. My vague recollection is that we just hadn't tested it any other way so we wanted to be safe.
