### ISSUE TITLE
Problem with parallel option

### ISSUE THREAD

**Issue by GwladysLambert** [ss3sim/ss3sim#228]
Ok this is most definitely a problem from my end but I am hoping the error message I get will look familiar to somebody who is used to parallel processing, which I am not. I can use the doParallel and foreach libraries in other contexts but when I am using the run_ss3sim function with arguments parallel=T and parallel_iterations=T it works the first time I turn Rstudio on (sometimes), but any subsequent time I try to use it it gives me the following error message:

> run_ss3sim(iterations=1:4, scenarios='D0-F1-cod', case_folder='cases', case_files=case_files, > > >om_dir=om, em_dir=em, parallel=T, parallel_iterations=T)
Running iterations in parallel.
automatically exporting the following variables from the local environment:
  dots, x 
explicitly exporting variables(s): substr_r
numValues: 4, numResults: 0, stopped: TRUE
got results for task 1
accumulate got an error result
numValues: 4, numResults: 1, stopped: TRUE
returning status FALSE
got results for task 2
numValues: 4, numResults: 2, stopped: TRUE
returning status FALSE
got results for task 3
numValues: 4, numResults: 3, stopped: TRUE
returning status FALSE
got results for task 4
numValues: 4, numResults: 4, stopped: TRUE
not calling combine function due to errors
returning status TRUE
Error in do.call("ss3sim_base", c(x, list(iterations = it_, bias_already_run = TRUE),  : 
  task 1 failed - "Missing Files in om : .ctl file 
Missing Files in om : .dat file 
Missing Files in om : ss3.par file 
Missing Files in om : starter.ss
      file 
Missing Files in om : forecast.ss file 
"

The function works when I turn the parallel arguments off. I have tried reinstalling all the packages but to no avail. Anybody has got any suggestion? 

Many thanks in advance

**Comment by colemonnahan** [comment]
@GwladysLambert are you doing this in dropbox, or some other folder that is being monitored? If so, this can cause a delay for when the file is available to be used (in this case copied to another folder), because the other program has rights to it. After a delay, it is free'd up. 

If this describes your situation, we have a solution built in: the argument `admb_pause` which gets passed to the `run_ss3model` function. You can see it here:
https://github.com/ss3sim/ss3sim/blob/master/R/run_ss3model.r#L34

and it does this `Sys.sleep(admb_pause)`. The default is 0.05, so maybe try setting that to something larger like 1. 

That's my first thought.

**Comment by GwladysLambert** [comment]
Just tried that but it did not change anything. Plus I had tried to put my folder on the C drive (as opposed to the NOAA server), and just tried again with this option you mention, but got the same error message

**Comment by jimianelli** [comment]
if using my computer...unsure if from R or Rstudio it may still be run over the shared noaa network thingy...anyway to do it at a command prompt?

**Comment by GwladysLambert** [comment]
I am working from my laptop (well noaa's), and tried unpluging from network, same error

**Comment by colemonnahan** [comment]
@GwladysLambert I agree with wise Jim. Try running it outside of RStudio, i.e., open up the native R GUI.

Also, when you navigate into the case folder where it gets stuck, what files do you see? In the OM and EM?

**Comment by GwladysLambert** [comment]
Yep, tried that too, it does not work in R either. And when it gets stuck it does not even creates any case or new iteration folder

**Comment by colemonnahan** [comment]
Hmm, that's a tough one. Hopefully @seananderson chimes in soon. He's the author of the parallel code for ss3sim and may have some deeper insights. I'll continue to think on it.

**Comment by kellijohnson** [comment]
@GwladysLambert are you installing the package from CRAN? @colemonnahan did not you have problems when trying to use the parallel functionality when installing the package with `devtools`? I cannot remember the issue exactly. Also, does the function work if you have multiple scenarios and try to run those in parallel instead of iterations? I doubt it, but it could be worth a try.

**Comment by GwladysLambert** [comment]
Ok @Kotkot  just popped in and looked at it. He had had similar issues and so it seemed that I had some Rscript.exe files that existed in the background  from past failed runs (although inactive) and had to be deleted manually (from the processes in task manager)... I don't know if that makes sense to anybody but the few runs I have tried after removing them have worked now, so I hope that was it. Thanks a lot everybody

**Comment by GwladysLambert** [comment]
Thanks Kelli I had tried that as well. I think the problem may be solved! I'll update here if there was anything else

**Comment by colemonnahan** [comment]
@GwladysLambert That's great. I remember Kot having those same issues. Basically it has to do with how these parallel processes are closed down. If they're left hanging around after an error (or maybe even normal termination) then it causes problems the next time you try to use them.

I think the hack solution is to open the task manager (Ctrl-Shift-Esc) and close any R processes directly. 
The best solution is to experiment with closing out Rstudio (or other program) so this doesn't happen. 

Please update if this isn't right, for future reference it will be a valuable solution.

**Comment by seananderson** [comment]
Glad you figured it out. Nothing more to add other than yes, that can happen with parallel processing. I think those processes can persist even if RStudio is quit. We could add a note in the vignette. On a Mac, the utility Activity Monitor is a quick way to find and force quit the parallel R processes.
