### ISSUE TITLE
Minor version update of ss3sim will be submitted to CRAN in a couple days 

### ISSUE THREAD

**Issue by seananderson** [ss3sim/ss3sim#229]
ss3sim was broken with the development version of dplyr, which will be submitted to CRAN on April 25. I fixed the issue and will submit ss3sim 0.9.1 in a couple days. If there are any minor changes you want to slip in before I submit then let me know.

**Comment by kellijohnson** [comment]
@seananderson I was going to close this issue, but how come when I go to https://github.com/ss3sim/ss3sim/releases it does not show 0.9.1? I know we have a CRAN comments page, but how do we get the release page to be updated?

**Comment by seananderson** [comment]
We do it manually :)

**Comment by kellijohnson** [comment]
done
