### ISSUE TITLE
Error in parallel execution: foreach call

### ISSUE THREAD

**Issue by cstawitz** [ss3sim/ss3sim#234]
I get an error trying to run scenarios in parallel - it occurs in foreach during the call on line 234:246 in run_ss3sim.r:
 foreach::foreach(x = arg_list, .packages = "ss3sim",
        .verbose = FALSE, .export = "substr_r") %dopar%
          do.call("ss3sim_base", c(x, list(iterations = iterations, ...)))

One on machine the error is: Error in do.call("ss3sim_base", c(x, list(iterations = iterations, ...))) : 
  task 1 failed - "comparison of these types is not implemented"

On the other it is :  Error in do.call("ss3sim_base", c(x, list(iterations = iterations, ...))) : 
  task 1 failed - "'from' and 'to' are of different lengths" 

Everything works fine in sequence. Any ideas? I have changed some stuff in the package, but it isn't even getting to ss3sim_base so I'm guessing this is unrelated.

**Comment by colemonnahan** [comment]
Can you report the packages versions for `foreach` and `parallel`? Have you updated them recently? Also what version of R?

**Comment by cstawitz** [comment]
One machine I installed R for the first time on about a week ago, so everything is the most recent version. The other is R version 3.3.1, `doParallel` version 1.0.10, and `foreach` version 1.4.3

**Comment by cstawitz** [comment]
None of them have updates more recent than that.

**Comment by colemonnahan** [comment]
@cstawitz Also a good idea to make sure you can run the example in `foreach`. If that doesn't run then it's a setup issue, if it does its probably on the `ss3sim` side.

**Comment by cstawitz** [comment]
Do you mean the basic example? I can run `x <- foreach(i=1:3) %do% sqrt(i)` no problem.

**Comment by colemonnahan** [comment]
Yeah that's what I had in mind. Hmm. Let's see if Sean can diagnose the error. We can try on a machine I know works if he doesn't get back soon.

**Comment by seananderson** [comment]
Not sure. Does the following run for you? It runs for me without errors.

```r
library(ss3sim)
temp_path <- file.path(tempdir(), "ss3sim-example")
dir.create(temp_path, showWarnings = FALSE)
wd <- getwd()
setwd(temp_path)

# Find the data in the ss3sim package:
d <- system.file("extdata", package = "ss3sim")
om <- paste0(d, "/models/cod-om")
em <- paste0(d, "/models/cod-em")
case_folder <- paste0(d, "/eg-cases")
# An example of a run using parallel processing across 2 cores:
require(doParallel)
registerDoParallel(cores = 2)
require(foreach)
getDoParWorkers() # check how many cores are registered

# parallel scenarios:
run_ss3sim(iterations = 1, scenarios = c("D0-F0-cod",
    "D1-F0-cod"), case_folder = case_folder,
  om_dir = om, em_dir = em, parallel = TRUE)

# Running scenarios in parallel.
# Completed iterations: 1 for scenarios: D0-F0-cod, D1-F0-cod

# clean up:
unlink("D0-F0-cod", recursive = TRUE)
unlink("D1-F0-cod", recursive = TRUE)
```

**Comment by cstawitz** [comment]
Hm @seananderson that works for me, but not using the new model and branch I created. So I guess it must have something to do with the changes I've made?

**Comment by colemonnahan** [comment]
I don't understand why your changes would run in serial but not parallel.  Is it possible to take the above example and slowly add your updated functionality? E.g., if you updated `change_tv` and `sample_calcomp` then add cases one at a time using the cod model? Might help get to the bottom of whether it is the model or your code.

Also, are you doing iterations in parallel or scenarios? If you're only running a single scenario you want to set `parallel_iterations` to TRUE in `run_ss3sim`. Maybe it throws an error there if there's only one scenario and you try to run it in parallel?

**Comment by cstawitz** [comment]
Yea I'm doing three scenarios across three cores.

I think it is something in my OM and EM files. It seems to work with my changes for the cod model but not for the new model.

**Comment by cstawitz** [comment]
Kelli helped me troubleshoot this - the issue only occurs when using `devtools::load_all` to install the package from a local directory. Installing from Git works fine.

**Comment by seananderson** [comment]
I seem to remember that being a Windows specific thing. The parallel scenarios seem to work fine on Unix machines with `devtools::load_all()`. The alternative is to use `devtools::install()`, which does a full local install without the tricks of `load_all()` at the expense of being a bit slower.

**Comment by colemonnahan** [comment]
I've had issues with `devtools::install` too I think. Best is to restart R
or at least clear the workspace before reinstalling.

**Comment by kellijohnson** [comment]
Now noted in the vignette with 993f284325fa9b2ae4835cc3059b46a27ffe780c.

**Comment by seananderson** [comment]
Thanks Kelli. Note that `devtools::install()` is the solution, not the problem. `devtools::install` is just a wrapper around `install.packages(..., repos = NULL)` with some useful defaults. I tweaked the vignette wording slightly: https://github.com/ss3sim/ss3sim/commit/99e4bd69187132c7371546a00d8f8141f13ca288

**Comment by kellijohnson** [comment]
Thanks @seananderson
