### ISSUE TITLE
Package dependencies

### ISSUE THREAD

**Issue by kellijohnson** [ss3sim/ss3sim#235]
Not all Imports of Imports are installed when executing
`install_github("ss3sim/ss3sim")`
For instance, `numDeriv`, which is an Import from `bbmle` is not installed, but it is correctly installed using
`install.packages("ss3sim")`
The issue  is a `devtools` error, and can be found at https://github.com/hadley/devtools/issues/1330.

Also occurs with `DBI`, which is an Import of `dplyr`

**Comment by seananderson** [comment]
If this makes the github version unusable for a new user then perhaps we should suggest running install.packages first to get all dependencies. Does this issue cause errors for a user starting without these packages?

**Comment by kellijohnson** [comment]
Correct, I just downloaded the newest version of R, so I was going to test #234, but `ss3sim` won't even load with
`devtools::install_github("ss3sim/ss3sim")
library(ss3sim)`
even though the first command does not fail.

I just reinstalled R again (version 3.3.1) to see if I get an error when calling
`install.packages(ss3sim)
library(ss3sim)'
and everything is good.

**Comment by taylori** [comment]
It would be nice if new users could go straight to devtools, but installing
from CRAN first doesn't seem too arduous.

There's at least one open issue with devtools related to installing
dependencies
https://github.com/hadley/devtools/issues/1298
as well as some closed issues where the comments suggest that the problem
wasn't with devtools:
https://github.com/hadley/devtools/issues/766

**Comment by kellijohnson** [comment]
Thanks @taylori. The problem has been fixed in the development version of `devtools`, which is 1.12.0.9, where the CRAN version is 1.12.0. The following code works to install `ss3sim`
```
install.packages("devtools", repos = "http://cran.us.r-project.org")
library(devtools)
install_github("hadley/devtools", force = TRUE)
detach("package:devtools", unload = TRUE)
library(devtools)
install_github("ss3sim/ss3sim")
library(ss3sim)
```
It looks like `devtools` is sent to CRAN approximately every 4 months, so soon it will not be an issue and people will just be able to use the CRAN version of `devtools`.

**Comment by colemonnahan** [comment]
Does this relate to the parallel issues that @cstawitz is having in https://github.com/ss3sim/ss3sim/issues/234?

**Comment by cstawitz** [comment]
No @colemonnahan , I've been manually installing all of the dependent packages, like `foreach` and `parallel`

**Comment by kellijohnson** [comment]
Noted how to update devtools in the README.md file with this [commit](8a4f65f402400430213a011110e30760c5163c00)

**Comment by taylori** [comment]
Note URL in previous comment was incorrect (included "/issues/" instead of "/commit/"). The following link should work for anyone following up on this issue: https://github.com/ss3sim/ss3sim/commit/8a4f65f402400430213a011110e30760c5163c00
