### ISSUE TITLE
get_results_all doesn't overwrite existing .csv

### ISSUE THREAD

**Issue by cstawitz** [ss3sim/ss3sim#237]
Running `get_results_all()` in a folder that already has files with the names "ss3sim_scalar.csv" and "ss3sim_ts.csv" doesn't overwrite or add to the .csv but silently fails. This is annoying when running multiple runs to troubleshoot. It seems like the function should either add to the existing .csv file, or overwrite them, or at least provide a warning that the user is about to read in old .csv files.

**Comment by seananderson** [comment]
I just wrote some more unit tests here: https://github.com/ss3sim/ss3sim/blob/master/tests/testthat/test-get-results.R

`get_results_scenario()` seems to work correctly for me, at least with the serial option. By default, `overwrite_files = FALSE`.

`get_results_all()` seems to pass the argument `overwrite_files = FALSE` correctly to the scenario level function. However, it looks like `get_results_all()` overwrites the main scalar and ts files no matter what. I think the idea was to avoid the slowness of reading all the scenario level files again. Although I guess it's a bit confusing that those main files get overwritten no matter what. 

@cstawitz Could you add a test that shows when `get_results_all()` doesn't overwrite the main .csv files if the files are already present?

**Comment by colemonnahan** [comment]
Yeah it should overwrite them per https://github.com/ss3sim/ss3sim/blob/master/R/get-results.r#L205 that uses the defaults. I'd also be surprised if parallel interacted with this since the writing occurs after pulling the results back in.

Could be some other issue caused a stop before writing?

**Comment by taylori** [comment]
Excel will often lock CSV files and prevent overwriting, even when the CSV
file has been closed but the Excel process is still open. This could easily
cause a failure to overwrite the files.

**Comment by cstawitz** [comment]
I interpreted Sean's response to mean the default was to NOT overwrite files. I have not been modifying that argument, so isn't not overwriting expected then?

**Comment by seananderson** [comment]
I believe the default is to not overwrite the CSV files in the scenario folders but the CSV files in the root folder (the files you referred to) should always get overwritten.

**Comment by taylori** [comment]
Yes, the code Cole linked to seems to indicate that the write.csv for
ss3sim_scalar.csv and ss3sim_ts.csv is not impacted by the value of
overwrite_files.

**Comment by cstawitz** [comment]
Ok then it is working as intended. I was expecting the default to be to overwrite the files in the scenario folder as well (results_dq_<scenario>.csv)

**Comment by colemonnahan** [comment]
The reason it does this is because usually you start with a smaller # of iterations, then increase more. If you increase more it won't recognize there are new iterations and skip that folder, so you won't get the new data. So inside the scenarios the .csvs need a switch to overwrite or not. The top level ones don't need it as far as I've seen, particularly because all it does is loop through the scenario ones quickly and write. The bulk of the work is the r4ss calls to process the Report.sso files.
