### ISSUE TITLE
Pearson residuals for composition data

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3sim#238]
At an early stage of ss3sim I had some code that grabbed the residuals for comp data and plotted it. It was experimental and never went anywhere. Unfortunately, I can't remember what I did with the code and can't seem to find it in the package. Gwladys was hoping to do something similar...

Does anyone remember? It's been 3.5 years. Yikes!

@kellijohnson I tried this for the M paper so maybe you have it on an old branch or dropbox folder or something?

**Comment by kellijohnson** [comment]
@colemonnahan check your email, I think I found the code that you want.

**Comment by colemonnahan** [comment]
@kellijohnson Thanks for digging that up. If anyone comes upon this thread later looking for this code, email me or Gwladys Lambert.
