### ISSUE TITLE
Bug in vignette example with change_tv

### ISSUE THREAD

**Issue by seananderson** [ss3sim/ss3sim#239]
I just received an e-mail with a bug report from running the first example in the vignette introduction. Indeed, I can reproduce it:

```R
library(ss3sim)
d <- system.file("extdata", package = "ss3sim")
case_folder <- paste0(d, "/eg-cases")
om <- paste0(d, "/models/cod-om")
em <- paste0(d, "/models/cod-em")

run_ss3sim(iterations = 1, scenarios =
  c("D0-E0-F0-M0-cod",
    "D1-E0-F0-M0-cod",
    "D0-E1-F0-M0-cod",
    "D1-E1-F0-M0-cod"),
  case_files = list(F = "F", D = c("index", "lcomp", "agecomp"),
    E = "E", M = "M"),
  case_folder = case_folder, om_dir = om,
  em_dir = em)
```

```
Error in strsplit(temp, " ")[[1]] : subscript out of bounds
```

I can track that down to this line with `traceback()`
https://github.com/ss3sim/ss3sim/blob/master/R/change_tv.r#L440

And the problem is that `NatM_p_1_Fem_GP_1_ENV` isn't found in the report. 

```
temp <- grep(x, ss3.report, value = TRUE)
Browse[1]> env.name
      NatM_p_1_Fem_GP_1 
"NatM_p_1_Fem_GP_1_ENV" 
Browse[1]> temp
character(0)
Browse[1]> strsplit(temp, " ")[[1]][1]
Error in strsplit(temp, " ")[[1]] : subscript out of bounds
```

That piece of code hasn't changed in years, so I'm assuming the problem is something else that is simple. I'm out of time right now. Is this obvious to anyone? 

MO-cod.txt:
```
# A sample case file for arbitrary M change_tv() arguments
function_type; change_tv
param; NatM_p_1_Fem_GP_1
dev; rep(0, 100)
```

**Comment by colemonnahan** [comment]
This is with the CRAN version using the packaged executables?

**Comment by seananderson** [comment]
Good point. Meant to check that... It works if the executable is in my path. Forgot that I had renamed the local executables for testing. Amidst all the error messages, I missed the line `sh: ss3_24o_safe: command not found`. So the problem seems to be that the executables bundled with the package aren't being found. Let me look into that ...

**Comment by kellijohnson** [comment]
Sorry for the delay in my response. @colemonnahan good catch. @seananderson if you are still having problems I can look at it this weekend b/c the `change_tv` is my baby, I just do not have time until Saturday. Sorry.

**Comment by seananderson** [comment]
Fixed the issue. It was a mistake I made a while ago: https://github.com/ss3sim/ss3sim/commit/f3f8f194fde78c03b5c2a98d954714851742e33f

In `change_tv`, `ss_bin` should have been `bin`. `ss_bin` was the name of the executable not the full path. Therefore, in the call to the executable, it only worked in that function if the executable was in the user's path.
