### ISSUE TITLE
Remove complexity from change_e

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [ss3sim/ss3sim#240]
remove natural mortality specifications from `change_e` and make it like any other function where you just use the parameter name to change it, as it stands right now it is confusing

**Comment by k-doering-NOAA** [comment]
@kellijohnson-NOAA do we want to address this as we update? I know you were doing some work on `change_e` and not sure if it included this or not.

**Comment by kellijohnson-NOAA** [comment]
@k-doering-NOAA noticed that change_e looks at the q parameters, but I am not actually sure if anything is changed. Need to look more closely at this to ensure that either q pars are added for data that is available or that users are given a proper warning message.

**Comment by k-doering-NOAA** [comment]
I also noticed today that we may need a warning if users try to change q parameters in the EM that aren't already in the OM, which I think is a requirement.

**Comment by k-doering-NOAA** [comment]
change_e has been simplified as described, so closing this issue.
