### ISSUE TITLE
time-varying CV of growth

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [ss3sim/ss3sim#245]
SS will allow you to enter time-varying values for growth CVs but they are not used to calculate the derived quantities. `change_tv` should be modified to not allow CV_young and CV_old to vary with time. It would be nice to implement a new way to change the parameter values in the par file for the OM rather than right now we can only change the EM with change_e and use time-varying parameters in the OM to change them.

**Comment by kellijohnson-NOAA** [comment]
@k-doering-NOAA can you comment on this issue and check off the following tasks with your development with respect to `change_o`
 - [ ] write a check in `change_tv` to ensure that CV_young, CV_old, and the stock recruitment parameters that should not be time varying are not being manipulated by the user
 - [ ] implement `change_o` so users can change the point estimate of a parameter in the OM

**Comment by k-doering-NOAA** [comment]
Sure - I think the way it is implemented now does not have these checks so I will add them. I will also work on `change_o` as described.

**Comment by k-doering-NOAA** [comment]
commits 3c9dd7c4a671d7d5923814419fd5ce4839fcff75 and be8708c7de0239a57c7b4192f11b0475f64d610e implement these, so closing issue.
