### ISSUE TITLE
Errors when no CPUE data

### ISSUE THREAD

**Issue by kellijohnson** [ss3sim/ss3sim#251]
### [Working with ss3sim_base.Rd examples](https://github.com/ss3sim/ss3sim/blob/5b64ec3270475036dfda4254c280c053bcd5dfad/R/ss3sim_base.r#L165)
When trying to fix the examples (#249) I found that if you don't have any CPUE data in your dat file, SS will create a data.ss_new file with CPUE fleet information, i.e., ```#_Fleet Units Errtype``` for each fleet. SS will not run with this new dat file. I am testing it on a 3.24 model. The error is not in ss3sim or r4ss but rather SS because the ss_new file is wrong. 
I am not sure of the best protocol here given that 3.24 is not the latest version of SS. @taylori would Rick want to fix this in the old tpl? Which would then mean that we need to place new executables in the ss3sim bin folder. Or do we check the dat file for CPUE and if none, then remove the lines of units and errtypes? Thank you in advance for suggestions on what to do.

**Comment by taylori** [comment]
I think models with no CPUE are pretty rare, hence this not getting caught before. Combining that with the phasing out of 3.24 use in general, I don't imagine that it's a high priority to make a new SS release in the 3.24 series. If it's important for ss3sim to work for no-CPUE models, I think a work around where those extra lines are removed from the dat file would be the best approach.

**Comment by kellijohnson** [comment]
Thanks @taylori. I had never run into the error before either because models without CPUE is not a high priority for ss3sim. An example had the wrong years, which was in turn leading to all the CPUE data being deleted and then ```r4ss``` couldn't read in the ss_new file. I think that I will just leave things as is, given that we are in the process of updating to v3.30.

**Comment by kellijohnson** [comment]
The example in ```ss3sim_base``` was fixed by changing the years to match the "new" cod model in 9006fd1554aa745ef9f34dddcbf29a48674631df.
