### ISSUE TITLE
Need more unit testing

### ISSUE THREAD

**Issue by k-doering-NOAA** [ss3sim/ss3sim#255]
Unit tests be added in the ss3sim version for 3.30 in development. Most important functions to add tests for (or check more thoroughly if tests are needed are:

- [x] change_rec_devs
- [x] change_f
- [x] calculate_data_units
- [x] clean_data
- [x]  add_nulls
- [x] change_data
- [x] sample_lcomp
- [x] sample_agecomp
- [x] change_em_binning
- [x] change_e

Has tests, but some broken and need to be fixed:
- [x] get_results_all

Some functions that maybe should be deprecated, and therefore tests could be removed if they are:
- [x] change_maturity
- [x] change_year

Big functions that already have a decent number of tests:
- [x] change_o
- [x] change_tv
- [x] run_ss3sim
- [x] sample_index

There are other functions lacking tests, but they are simpler so less likely to break.

I will work on adding tests and check them off as I go.

**Comment by kellijohnson-NOAA** [comment]
I might have fixed the code for get_results_all already, but the fix is on a different computer. I will look tonight and push.

**Comment by k-doering-NOAA** [comment]
> I might have fixed the code for get_results_all already, but the fix is on a different computer. I will look tonight and push.

great, thank you!

**Comment by kellijohnson-NOAA** [comment]
> > I might have fixed the code for get_results_all already, but the fix is on a different computer. I will look tonight and push.
> 
> great, thank you!

I had pushed all of the changes that I had to `get_results_all` already. I am going to try running through some of the tests that are commented out today to help. Starting with `change_f`

**Comment by k-doering-NOAA** [comment]
Sounds good! I will start with `change_data` and will move on to `calculate_data_units`, `clean_data` and `add_nulls`, time permitting.

**Comment by k-doering-NOAA** [comment]
I think tests sufficiently cover the most important functions as of 61c6dfd29e9be4e6caa4409351092e015cf6f906. However, 1 test in test-run-ss3sim is still not working and tests in get-results are not, either. I will work on these.

@kellijohnson-NOAA do you have an opinion on deprecating change_maturity and/or change_year?

**Comment by k-doering-NOAA** [comment]
3f3caf9edce3ea55e500278466bbe634f68a50c8 fixes all tests, so adding unit tests and fixing broken ones now complete.
