### ISSUE TITLE
change_F not robust to  ctl files with F method = 1 or 3

### ISSUE THREAD

**Issue by k-doering-NOAA** [ss3sim/ss3sim#256]
While developing tests (as in issue #255 ), I discovered that change_f cannot handle when the control file does not have detailed inputs for F. It can handle:

```
#Fishing Mortality info
0.3 # F ballpark
-2001 # F ballpark year (neg value to disable)
2 # F_Method:  1=Pope; 2=instan. F; 3=hybrid (hybrid is recommended)
4 # max F or harvest rate, depends on F_Method
# no additional F input needed for Fmethod 1
# if Fmethod=2; read overall start F value; overall phase; N detailed inputs to read
# if Fmethod=3; read N iterations for tuning for Fmethod 3
 0.2 1 1 # overall start F value; overall phase; N detailed inputs to read
#Fleet Yr Seas F_value se phase (for detailed setup of F_Method=2; -Yr to fill remaining years)
 1 1 1 0.004 0.005 -1
#
```

But gets inputs out of order with:
 ```
#Fishing Mortality info
0.3 # F ballpark
-2001 # F ballpark year (neg value to disable)
3 # F_Method:  1=Pope; 2=instan. F; 3=hybrid (hybrid is recommended)
4 # max F or harvest rate, depends on F_Method
# no additional F input needed for Fmethod 1
# if Fmethod=2; read overall start F value; overall phase; N detailed inputs to read
# if Fmethod=3; read N iterations for tuning for Fmethod 3
4  # N iterations for tuning F in hybrid method (recommend 3 to 7)
#
```
To address this:
- [x] Modify change_F (https://github.com/ss3sim/ss3sim/blob/update_cod_3.24/R/change_f.r) to work with F methods 1 and 3 in the initial control file, or at least add informative error message to warn users that it won't work
- [x] Develop https://github.com/ss3sim/ss3sim/blob/update_cod_3.24/tests/testthat/test-change_f.R#L128-L132 so that it passes (i.e., works with F methods 1 and 3 as expected or provides expected error)

@kellijohnson-NOAA I am assigning you only because you developed the function; I am happy to tackle this instead if you would like.

**Comment by k-doering-NOAA** [comment]
@kellijohnson-NOAA would you like me to work on this? I only assigned you initially because I think you were actively developing change F, but this is no longer the case. Do you thing just adding the stop message for now is adequate? Because it is only used to manipulate the OM  and not EM, I think we only need the instantaneous F (method  = 2 ) to be supported, but I think we should warn users if they chose the wrong option?

**Comment by kellijohnson-NOAA** [comment]
Sure, that would be great @k-doering-NOAA. The only reason we would ever want something different is if we allow `ss3sim` users to input catches instead of fishing mortality levels, which we currently don't allow. So, a stop statement would be sufficient for right now and then maybe in the project board (or issues) we can find a spot for a new features list with a way to prioritize them?

**Comment by k-doering-NOAA** [comment]
Great, I will add stop statements for now, but agree that allowing users to input catches instead of F would be a useful development. I think trying to prioritize new features would be a great test to see if a project board is helpful.

**Comment by k-doering-NOAA** [comment]
ca0581eefbba4d2ada05d02caef0ac8179994c83 adds stop message and test.
