### ISSUE TITLE
deprecated dplyr functions used in change_em_binning

### ISSUE THREAD

**Issue by k-doering-NOAA** [ss3sim/ss3sim#258]
https://github.com/ss3sim/ss3sim/blob/update_cod_3.24/R/change_em_binning.r#L239-L256 includes dplyr functions like `group_by_()` that have been deprecated. The normal versions, like `group_by()` should be used instead. For now, these functions are still supported, but they may not be in the future.

**Comment by seananderson** [comment]
If that’s the only place it’s used then it might be worth just rewriting it
to avoid dplyr because dplyr evolves quickly and has lots of dependencies.
If you keep it then drop the underscores, import .data from rlang, and put
.data$ in front of each unquoted column name (the things with tildes in
front of them right now). I can point you to examples or do it if needed.

**Comment by kellijohnson-NOAA** [comment]
I don't know `dplyr` as well as I should so I advocate for removing it to make things easier for me to maintain. Looks like we might be able to use `aggregate` or something along those lines because I think we are just summing across groups. I will need to look at the code more.

**Comment by k-doering-NOAA** [comment]
Thanks @seananderson  and @kellijohnson-NOAA , I also agree that it makes sense to remove it, if possible. dplyr is only imported in scripts change_em_binning.r, change_data.r, and clean_data.r . 

In clean_data, I needed to do some data manipulation that I wasn't sure how to do without dplyr (I know dplyr fairly well, but at the expense of not knowing how to manipulate data with base R) : https://github.com/ss3sim/ss3sim/blob/development/R/clean_data.r#L69-L73

**Comment by seananderson** [comment]
`aggregate()` would work or the good old-fashioned `split()`, `lapply()`, `do.call(rbind())`. See this nice [summary](https://coolbutuseless.bitbucket.io/2018/03/03/split-apply-combine-my-search-for-a-replacement-for-group_by---do/) (see "Prehistoric times", ha). Same approach could work for that clean data function. The `complete(nesting(...` part could be replaced with an `expand.grid()` + a `merge()`. I'm a huge dplyr fan, but given it's used in so few places here it might be worth removing. We had to submit updates to CRAN before as dplyr evolved.

**Comment by k-doering-NOAA** [comment]
c9620d2198e2e89f50f2853378ab51f4f749f9e8 removes dplyr code, and replaces it with functions like `aggregate` and `merge`. Thanks @seananderson  for the suggestion and @kellijohnson-NOAA  for helping get this done.
