### ISSUE TITLE
refactor profile_fmsy to not use .par file 

### ISSUE THREAD

**Issue by k-doering-NOAA** [ss3sim/ss3sim#261]
Currently, profile_fmsy requires a model with a .par file, which means it cannot be run with codOM, which lacks a .par file. 

I think this should be possible to do, given that we no longer use the .par file for any of the other OMs. Alternatively, I think the function could be rewritten so that it can create a .par file from other model files if needed.

For now, the example has been commented out. This function is not used elsewhere in ss3sim, so updating it is a relatively low priority.

**Comment by kellijohnson-NOAA** [comment]
Fixed with 6b325b6 that uses change_f rather than change_f_par allowing for the OM that comes with the package to be used.
