### ISSUE TITLE
development branch badges on readme show status for master, not development

### ISSUE THREAD

**Issue by k-doering-NOAA** [ss3sim/ss3sim#264]
I think this should be an easy edit (change branch referenced here: https://github.com/ss3sim/ss3sim/blob/development/README.Rmd#L20-L22), but I wasn't sure exactly how we wanted to do this.

 Should we show both the master and development branch badging statuses on the readme (for both master and development branches?)The advantage I see in this is no need to change which branch they reference when merging development into master.

Or, we could change the badges in the readme on the development branch to be for the development branch.

**Comment by kellijohnson-NOAA** [comment]
My preference would be to have both the master and development branch build status rather than switching back and forth. Especially because we are advocating for people to install the development branch.

**Comment by kellijohnson-NOAA** [comment]
Looks like we need to add better labels, though I do have the build icons there for both branches now with b316e5e

**Comment by k-doering-NOAA** [comment]
Looks great, I added labels in 643e4fd22f05542396c53d6ac74ff55fa5a1333b .
