### ISSUE TITLE
Feature request for profile_msy 

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3sim#267]
@kellijohnson-NOAA I tweaked a single selex parameter in the cod OM and `profile_msy` failed to run due to purported non-equilibrium state:

````
Error in profile_fmsy(om, results_out = "fmsy", start = 0.01, end = 0.2,  : 
  The population doesn't appear to be reaching equilibrium, 
the model should be ran for more than 100 years.
````
I kind of doubt this is the case here but it would be nice to be able to see the resulting curve so I request the `stop` be converted into a `warning` and to add a new column onto the output which is the criterion used to determine equilibrium or not. Then the user can see which years are bad, and really only the FMSY is important, not the tails. That is, the function shouldn't fail when the equilibrium catch is close to 0 b/c those have no effect on the estimation of FMSY.

**Comment by kellijohnson-NOAA** [comment]
I used verbose to allow users to print the message to the screen.
