### ISSUE TITLE
More detailed tutorial?

### ISSUE THREAD

**Issue by mingsun** [ss3sim/ss3sim#268]
Great package. I am just wondering if you have a more detailed tutorial?

**Comment by kellijohnson-NOAA** [comment]
@mingsun thanks for checking the package out. There are a few vignettes that you can build after you clone the package or are available if you install it using R (i.e., `remotes::install_github(build_vignettes = TRUE)`). Beyond that, we done a few workshops and I can provide those presentation if you email [me](mailto:kelli.johnson@noaa.gov).

**Comment by lpfeif** [comment]
Hi Kelli, I was trying to work through the vignettes, and at least the first one seems to be a bit out of date. "Error in FUN(X[[i]], ...) : 
  Parameters in change_e: natM_type, natM_n_breakpoints, natM_lorenzen, and natM_val have been deprecated and cannot be used."
Do you have advice on a vignette or something similar to work through that will run with the current version? Thanks!

**Comment by kellijohnson-NOAA** [comment]
The best example to work through currently is the one in ss3sim_base from the development branch. We are working on updating all of the examples and the vignette, though that will come last. Sorry about that. Please let me know if you have any specific questions. I am happy to help.

**Comment by kellijohnson-NOAA** [comment]
The vignette has been updated to work with the package in its current state.
