### ISSUE TITLE
return() from copy_ss3models is just for last model

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [ss3sim/ss3sim#276]
https://github.com/ss3sim/ss3sim/blob/fad28e25ed1617c6feb103b6434d3158514960d2/R/copy_ss3models.r#L62

iteration_exists is not a vector, instead it is a single entry for only the last scenario/iteration that was copied. The function is not used in vector form though within ss3sim, so technically it is not leading to an error though it is bad coding.

Think about using `r4ss::populate_multiple_folders` instead, or at least `r4ss::copy_SS_inputs`

**Comment by iantaylor-NOAA** [comment]
As always, if there are changes to the `r4ss` functions (e.g. `populate_multiple_folders` or `copy_SS_inputs`) which would make things easier for `ss3sim`, please feel free to make them.
