### ISSUE TITLE
ss3sim doesn't run without comp data for fishery or with an index for fishery

### ISSUE THREAD

**Issue by k-doering-NOAA** [ss3sim/ss3sim#279]
Reporting some scenario combinations that didn't work for me, either resulting in EM models that don't run (run_ss3sim runs all the way through, despite this), or an error. I think these should run, but don't? If they are not supposed to run, perhaps a more helpful error should be added to inform the user.

1. Running ss3sim scenario without compdata (no age or length) for the fishery - runs fine as long as one is included. Reprex:
``` r
df1 <- setup_scenarios_defaults()
#the below works, nonzero catch:
run_ss3sim(iterations = 1, simdf = df1)
# delete the length comps cols for fleet 1 so there are no comps or index
# for fleet 1
df_nocomps_1 <- df1
df_nocomps_1$sl.Nsamp.1 <- NULL 
df_nocomps_1$sl.years.1 <- NULL
df_nocomps_1$sa.Nsamp.1 <- NULL 
df_nocomps_1$sa.years.1 <- NULL
# no catches in data.ss_new for om, so em doesn't run (even tho ss3sim says it completes)
run_ss3sim(iterations = 1, simdf = df_nocomps_1) 
```

2. Running ss3sim scenario adding in an index for the fishery - results in an error. Reprex:
``` r
df_index_comp_1 <- setup_scenarios_defaults()
df_index_comp_1$si.years.1 <- df_index_comp_1$si.years.2
df_index_comp_1$si.sds_obs.1 <- "0.1"
run_ss3sim(iterations = 1, simdf = df_index_comp_1)
# get this error:
# Error in change_q(string_add = qtasks$add, string_remove = qtasks$remove,  : 
#                     Either string_add or string_remove must have an entry.
```

**Comment by k-doering-NOAA** [comment]
@kellijohnson-NOAA, your explanation for 1) makes sense  thanks for taking a look so quickly.

I did a little more testing and it seems like SS itself fails to generate catch from the OM when there is no comp data of any type for the fishery (fleet 1) - however, it will work if there is no comp data for the survey (fleet 2). I think this is just due to missing some lines of dummy data for comps when running the OM. To me, it seems there are 2 solutions:

A) Add a stop to alert the user when the OM did not generate catch (all catch is 0)
B) Add a stop to alert the user when the OM did not generate catch (all catch is 0) AND Even if the user doesn't want to sample comp data for the fishery (or more generally, any fleet), allow them to by adding some comp data for the fishery to run the OM, but then don't sample from the expected values. I think this would allow OMs to run properly, therefore allowing users to run EMs without comp data for the fishery (for example, if they have fixed selectivity, like you mentioned.

Thoughts on whether A) or B) (or something else) is a good solution? I would be happy to try to write the code.

Also, thank you for the quick fix on 2) - I tested and it worked for me!

**Comment by kellijohnson-NOAA** [comment]
Do you think that the failure to generate catch should be changed within SS?

**Comment by k-doering-NOAA** [comment]
That's a good point, Kelli. I will look more into this and see if it seems feasible to change in SS.

**Comment by k-doering-NOAA** [comment]
I figured out that there is actually an ss3sim bug which causes the fleet for catch data to change from 1 to 2, where 2 is a survey - so SS seems to be working as expected and generating 0 catch. When I run:
```r
df_nocomps_1 <- setup_scenarios_defaults()
# delete the length comps cols for fleet 1 so there are no comps or index
# for fleet 1
df_nocomps_1$sl.Nsamp.1 <- NULL 
df_nocomps_1$sl.years.1 <- NULL
df_nocomps_1$sa.Nsamp.1 <- NULL 
df_nocomps_1$sa.years.1 <- NULL
# no catches in data.ss_new for om, so em doesn't run (even tho ss3sim says it completes)
run_ss3sim(iterations = 1, simdf = df_nocomps_1) 
```
Then look in the iteration 1 om folder for the file called ss3.dat , I see for catches:
```r
#_Catch data
#_year	season	fleet	catch	catch_se
 -999	1	2	0	0.01	#_1         
    1	1	2	1	0.01	#_2         
    2	1	2	1	0.01	#_3         
    3	1	2	1	0.01	#_4         
    4	1	2	1	0.01	#_5         
    5	1	2	1	0.01	#_6         
...
```
when I would expect to see:
```r
#_Catch data
#_year	season	fleet	catch	catch_se
 -999	1	1	0	0.01	#_1         
    1	1	1	1	0.01	#_2         
    2	1	1	1	0.01	#_3         
    3	1	1	1	0.01	#_4         
    4	1	1	1	0.01	#_5         
    5	1	1	1	0.01	#_6         
...
```

The catches for fleet 2 (and removal of catches for fleet 1) happens in https://github.com/ss3sim/ss3sim/blob/master/R/change_data.r#L131-L133 . It looks like this code was added in order to allow multiple fleets to work with ss3sim, but it isn't working properly in this case (because the argument fleets = 2 is passed to this function).

I think this problem occurs b/c the function is passed in only the fleets needed to sample comps (or mean size or mean size at age), but then the fleets for catch is modified on these sample comp fleets. Specifically, in this case, no comps are sampled for fleet 1, so fleets = 2 and the catches for fleet 1 are removed and replaced with lines of catch for fleet 2. 

@kellijohnson-NOAA do you have thoughts on how to fix this? Maybe a separate fleets for catch argument needs to be passed to the function?

**Comment by kellijohnson-NOAA** [comment]
Wow that was buried. Nice work.
I think the best option is to pull out generating catch from this function and make two new functions `calculate_catch_units()` and `change_catch()` or something like that and create catches for whatever fleets we need.

**Comment by k-doering-NOAA** [comment]
That sounds like a great idea to make separate functions for manipulating catch, thanks, Kelli! I will add this to my "to do" list, but have added a blanket stop statement for 0 catches in commit eb10d6664bc796fabb12fc29e6db298f6e39e05e in the meantime (although this isn't yet merged into development)
