### ISSUE TITLE
issues with specifying a om or em dir 

### ISSUE THREAD

**Issue by k-doering-NOAA** [ss3sim/ss3sim#285]
I had some issues with specifying my own path to an om dir while using the default em dir. I am noting them here as a reminder to fix later:
- [x] I thought I had to specify the om_dir through the om_dir input to `run_ss3sim`, but this didn't work. I think it is ignored if there is a `simdf` provided. Perhaps the fix for this is providing a warning or error if both a simdf and either om_dir or em_dir are provided?
- [x] I also ran into issues specifying in the simdf. I thought initially that providing a column called "om_dir" would work, but it ran into issues b/c [ss3sim adds an "om" column, too](https://github.com/ss3sim/ss3sim/blob/development/R/setup_scenarios.R#L40-L46). I think the fix is to change the names of the `musthavecols` in `setup_scenarios_fillmissing` from om and em to om_dir and em_dir (although then the user couldn't provide cols called "om" and "em") or to come up with a way to allow partial matching such that a user could add a column called "om" or "om_dir" and either would work fine.
- [x] Specifying a path that didn't use "/" (but instead "\\") for the OM didn't work, I think due to this line of code: https://github.com/ss3sim/ss3sim/blob/development/R/copy_ss3models.r#L54 There is probably an easy fix for this that doesn't require assuming a particular separator in the file path.
- [x] I had to specify both the path to the OM and EM directories, as I got an error when only specifying the path to the OM:
 ```
Error in copy_ss3models(model_dir = em_dir, scenarios = sc, iterations = i,  : 
  argument "em_dir" is missing, with no default
```

I think all of these issues will require pretty minor changes, so I should be able to fix them shortly.
In the meantime, I was able to successfully specify my own om by adding it as a column called "om" in the simdf using a path with "/" separators, and also adding a path to the em in a column called "em" in the simdf. So, there is a workaround!

**Comment by k-doering-NOAA** [comment]
All of these were fixed in the commits above (in a separate branch for now)

@kellijohnson-NOAA feel free to comment if you see any problems with these issues...

**Comment by kellijohnson-NOAA** [comment]
I made a few comments, but feel free to pull in the changes whenever you feel this is wrapped up.
