### ISSUE TITLE
Effective se_log in `sample_index`

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [ss3sim/ss3sim#296]
## Goal
Implement effective error in index sampling.

## Current
When sampling the index with `sample_index` one should really think about if se_log should be left as the true value used to sample from the expected values, the original value in the dat file with expected values, or some effective sd like how in the length composition you can specify ESS.
This matters for estimating the index in the EM, specifying the wrong variance might make the model fit worse.

## Proposal
New input argument ...?

**Comment by k-doering-NOAA** [comment]
I agree, I think the new input argument approach as in the comps sampling functions is the right way to go about this.

**Comment by kellijohnson-NOAA** [comment]
Thanks to @lcitores for reminding me about this needed feature. Hoping to implement it today with the following logic:
- [ ]Add an argument to sample_index called sds_out.
- [ ] Write an if statement for when sds_out is missing(sds_out) that assigns values using sds_obs.
- [ ]Double check that it is in the same form as other input argument and if not, then expand it. See code for sds_obs.
- [ ] Set the sd of the output file using sds_out prior to the return() call.

@lcitores how is this going, do you need any help? Feel free to email me files or push changes to a new branch or the weight-at-age branch (fix-wtatage).
