### ISSUE TITLE
change_f doesn't account for equilibrium catch F parameters

### ISSUE THREAD

**Issue by k-doering-NOAA** [ss3sim/ss3sim#302]
The code in change_f strips out any equilibirium catch F parameters (that are only needed if there is non-zero equilibirium catch in the datafile). These inputs occur between the initF parameters and the q setup, but change_f consideres the q_setup the end of the initF values: https://github.com/ss3sim/ss3sim/blob/development/R/change_f.r#L119

Therefore, any operating model in ss3sim cannot use equilibirum catch currently. 

Investigate if there is a need for and way to keep including equilibirium catch in operating and estimation models.

Thanks to @peterkuriyama for reporting this!

**Comment by kellijohnson-NOAA** [comment]
The current code is only based on my limited knowledge of equilibrium catches, so I am open to any contributions to change this to accommodate what @peterkuriyama needs for sardine. Can equilibrium catch be provided as an F like the remainder of the time series?

**Comment by kellijohnson-NOAA** [comment]
ce9bd1c implements equilibrium catch for any fleet or season in the OM. @peterkuriyama can you please let us know if this works for you? This is a generalized approach rather than a specific one for fleet 1 as in your pull request.
