### ISSUE TITLE
Change ss3sim branches; just use main

### ISSUE THREAD

**Issue by k-doering-NOAA** [ss3sim/ss3sim#305]
@iantaylor-NOAA suggested for the package r4ss [to only use one main branch instead of master/dev branches](https://github.com/r4ss/r4ss/issues/496) . @kellijohnson-NOAA and I think this strategy would also work well for ss3sim, as 1) we consider the development branch more reliable than master almost always and 2) the user can access a version identical to the latest CRAN version through github releases rather than needing a master branch that mirrors it. The suggested changes are:
- [x] Merge any commits from master into development and delete the master branch
- [x] <del>Create a new branch "main" off of development that will be considered the most up to date version of ss3sim. Make this the default branch on github. </del>Rename master to main
- [x] Delete development
- [x] Update installation instructions for users.

Note that with this new system, we will want the main branch to remain reliable, so except for very minor changes, all work should probably be done in a feature branch (or off of a fork) and then submitted as a pull request. This will ensure that the code is tested by through github actions before being merged into main.

@kellijohnson-NOAA does this line up with what you were thinking? If anyone else has comments, please feel free to add. These changes won't be made for a few days in order to give folks a chance to respond.

**Comment by kellijohnson-NOAA** [comment]
Thanks @k-doering-NOAA for working on this. I think you captured everything except the timeline to push to CRAN. I would like to see new versions of r4ss and ss3sim on CRAN shortly after SS releases. @iantaylor-NOAA do you think that will be okay?

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA, that plan sounds fine.

I think it would be even better would be r4ss and ss3sim on CRAN right before the SS release. In the past a host of bug-fixes appeared after the release when more people were using the new version, but thanks to @k-doering-NOAA, the testing is more robust so we should be able to work out most of the bugs in the pre-release versions. Also, it seems like at least the 3.30.17 release is not expected to include a lot of input/output changes that would break ss3sim or r4ss.
