### ISSUE TITLE
misleading line in vignette about `change_tv` column

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [ss3sim/ss3sim#315]
I think this might be an outdated line in the vignette (section 4.1):

_The change_tv function can be used for a number of purposes. To pass arguments to change_tv through run_ss3sim you need to create a column labeled tv_params that holds code to generate a list of named objects that is passed to change_tv_list in change_tv._

This implies the name of the `df` column should be `change_tv` but I see it should be `ct.<name of parameter>` so I propose changing to:

_The change_tv function can be used for a number of purposes. To pass arguments to change_tv through run_ss3sim you need to create a column labeled 'ct.<parameter name>' that holds code to generate a list of named objects corresponding to this parameter name that is passed to change_tv_list in change_tv._

**Comment by kellijohnson-NOAA** [comment]
Thank you @ChristineStawitz-NOAA. https://github.com/ss3sim/ss3sim/blob/50606b75f9486fab62d12c1b7896b78b4191a29a/R/setup_scenarios.R#L243 confirms your thoughts. I will edit the vignette now, and thanks for providing suggested text.
