### ISSUE TITLE
update ss3sim to use SS3.30.19

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [ss3sim/ss3sim#335]
It has already been 19 days since SS3.30.18 was released and I still haven't updated ss3sim :disappointed:

**Comment by k-doering-NOAA** [comment]
I just realized we are still using 3.30.16 in main!

**Comment by kellijohnson-NOAA** [comment]
Use newest release of 3.30.19 instead of 3.30.18 as the title suggests. This may require some code changes because of the new file structure.

**Comment by k-doering-NOAA** [comment]
I've started working on  automated job to update to new versions of SS3: https://github.com/nmfs-stock-synthesis/workflows/issues/6

**Comment by kellijohnson-NOAA** [comment]
- [ ] update the cod model files using ss_new files so the comments in the files reflect the those placed in the files by the latest version of SS3
