### ISSUE TITLE
orphaned package gtools

### ISSUE THREAD

**Issue by k-doering-NOAA** [ss3sim/ss3sim#383]
I'm getting a warning in R CMD CHECK for SSMSE:
` Requires (indirectly) orphaned package: 'gtools'`

It's not clear to me if this will be "fixed" at some point in the future (gtools will become unorphaned) or we should do away twith the dependency.

I checked and gtools is a dependency of ss3sim (r4ss includes it as a suggest.)

It looks like it is only used in 1 line for the dirichlet distribution:
https://github.com/ss3sim/ss3sim/blob/edf728083c2d3720ca8fccc789ef4067a424d74c/R/sample_dm.R#L15
I wonder if it could be moved to suggests, or maybe replace the function with a new one internal to ss3sim?

**Comment by kellijohnson-NOAA** [comment]
Thanks @k-doering-NOAA for noticing this and posting an issue. I am not certain how to determine if the code can be copied and placed in {ss3sim} as an internal? Maybe @iantaylor-NOAA could provide guidance here? @Cole-Monnahan-NOAA do you have any ideas as well regarding sample from a random dirichlet distribution and if this functionality should be left in {ss3sim} or revamped? Thank you all for taking the time to provide guidance here.

**Comment by k-doering-NOAA** [comment]
I just found this thread: https://github.com/r-gregmisc/gtools/issues/15

Looks like it might get a new maintainer soon, so perhaps we just sit and wait for now!

**Comment by iantaylor-NOAA** [comment]
The {gtools} package was flagged for future removal as dependency from {r4ss} a while ago (see https://github.com/r4ss/r4ss/issues/376) but I haven't put any work into doing so. It's just the `gtools::running()` function that gets used to compute a moving average. 

{gtools} has a GPL-2 license which would allow copying code directly into the current {r4ss} which is also GPL, but not into {ss3sim} which has an MIT license (which is more permissive and a better match for NOAA policies). However, there's a long term goal to move {r4ss} to a different license that matches NOAA policy (see https://github.com/r4ss/r4ss/issues/625) so I don't think copying the code directly would help that. I suspect that there's some other source for the dirichlet distribution as @Cole-Monnahan-NOAA suggests, or you could just write some code that was similar to but not identical to the {gtools} implementation.

**Comment by iantaylor-NOAA** [comment]
I should also note that Greg Warnes, the author/maintainer of {gtools} was also author/maintainer of {gdata} which had similar problems and got removed from the {r4ss} dependency list (see https://github.com/r4ss/r4ss/issues/424). So I wouldn't count on it quickly getting unorphaned.

**Comment by Cole-Monnahan-NOAA** [comment]
The link shared by @k-doering-NOAA above has volunteers lined up for both so I feel confident about it.

**Comment by iantaylor-NOAA** [comment]
@Cole-Monnahan-NOAA, sorry, hadn't looked at that linked issue before posting.
Yes, seems like good folks have stepped up to keep these things alive.
But also raises the question about whether adding a dependency is the best way to add a single function.

**Comment by Cole-Monnahan-NOAA** [comment]
It's a good pint. Surely we can move it to depends or recommends? I kind of forget the specifics now, but dependency is not best practices for a single, rarely used function.

**Comment by kellijohnson-NOAA** [comment]
As of 2022-06-24 Ben Bolker has kindly taken over {gtools} and it is no longer orphaned. See [this commit](https://github.com/r-gregmisc/gtools/commit/33bea504b2574425693e3b5653a40b8ddf03fb2a). Thank you Ben 🥇
