### ISSUE TITLE
Make use of r4ss::run() and other functions for moving files and running models?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [ss3sim/ss3sim#385]
The r4ss issue https://github.com/r4ss/r4ss/issues/460 "create a single function for running SS models for use in r4ss, SSMSE, and ss3sim" has been resolved thanks to PR https://github.com/r4ss/r4ss/pull/722 so the modified functions are available for use in ss3sim. I'm not sure it's worth making changes here if the status-quo functions are working, but future developments could consider moving to the new r4ss functions.

**Comment by kellijohnson-NOAA** [comment]
Thanks @iantaylor-NOAA for reminding me to use `r4ss::run()` because I ❤️  any chance at reducing the amount of code that needs to be maintained.
