### ISSUE TITLE
Parallel processing function error

### ISSUE THREAD

**Issue by chamberlindw** [ss3sim/ss3sim#399]
https://github.com/ss3sim/ss3sim/blob/7f9850c78052657ad43445bad72bc59c283eb473/R/run_ss3sim.r#L145-L162

The parallel processing function in run_ss3sim seems to not be working. I tried running both my own SS model and the built in cod model with parallel = TRUE. Both models returned the same error below.

Running scenarios in parallel.
Error in eval(a, envir = extra, enclos = obj$evalenv) : 
  argument is missing, with no default

**Comment by peterkuriyama-NOAA** [comment]
I *think* there may be a stray comma in 152 after TRUE. Deleting it seems to have worked for me
