### ISSUE TITLE
forecast_num argument in change_e needs to be unlisted

### ISSUE THREAD

**Issue by okenk** [ss3sim/ss3sim#417]
Most arguments in `change_e()` are checked to make sure they are scalars/vectors. If they are lists, the `unlist()` function is applied. However, this is not applied to the `forecast_num` argument. If `change_e()` is called from `ss3sim_base()` via `run_ss3sim()`, you will get an error because it tries to subtract `forecast_num`, a list, from `dat_list$endyr`, an integer.

Once I unlisted the argument, it still didn't work. I guess `r4ss::SS_write()` does not like things that are supposed to be scalars being named, and it prints their names, which confuses SS3. Once you remove the name of `forecast_num` (carryover, not important), it works.

[This commit](https://github.com/okenk/ss3sim/commit/1ed395fa975dc3da4dd0a4901730ddc79850b8e2) should fix it. You can ignore the deletions-- there were a couple commits I thought would work and didn't.

**Comment by kellijohnson-NOAA** [comment]
Thank you so much @okenk and sorry this was not working for you. I don't think that we have tested a model with forecasting since I converted over to using the input data frame rather than input files. Thanks for showing me the fix as well. I cherry-picked the commit and it is now in main.

**Comment by kellijohnson-NOAA** [comment]
Two commits because I forgot to remove the names from the list even though I was guided to do so.
09085a2e
a97e11e27aa2e9802ef7b6e83cf3502305b0ee72
