### ISSUE TITLE
get_results_timeseries function - possible to sum TS values across areas?

### ISSUE THREAD

**Issue by skylersagarese-NOAA** [ss3sim/ss3sim#422]
We are working on creating OMs with the SSMSE package, which borrows from ss3sim. For summarizing time series results for a 2-area model, the get_results_all function from ss3sim ([get-results.r](https://github.com/ss3sim/ss3sim/blob/main/R/get-results.r)) does not retain “Area” in the time series and instead includes 2 lines for each year (one line for each region). Is it possible to revise the code to sum the TS values by year in 2-area models (specifically within the get_results_timeseries function)? We can do this on our end, but just wanted to submit this in case this is possible to modify. Thank you in advance!

**Comment by kellijohnson-NOAA** [comment]
No problem @skylersagarese-NOAA. I can add this over the weekend.

**Comment by skylersagarese-NOAA** [comment]
Great, thank you @kellijohnson-NOAA!
