### ISSUE TITLE
SS3 warns "Error trying to open data input file ss3.dat"

### ISSUE THREAD

**Issue by seananderson** [ss3sim/ss3sim#59]
Cole mentioned this. Pasting some emails here so we can keep track of this issue:

Cole: 

> "Error trying to open data input file ss3.dat"
> 
> The strange thing is in the em folder the starter.SS file has
> "data.dat" as the input file.

Sean:

> Hasn't it always thrown that warning? I think the next line indicates
> that it figured things out. I've been meaning to look into it. For some
> reason it looks for ss3.dat first and then reads the starter.SS file and
> finds data.dat.
> 
> The warning might be more obvious now because the default behaviour is
> to suppress all the other output. Before it was lost in a sea of output.
> 
> Thoughts? I assume the answer is simple.

...

Sean:

> We should throw a browser() statement in right before the SS3 call and
> then play on the command line to see what's happening.
> 
> One of those little bugs I hoped would just disappear if I ignored it
> long enough. But probably smart to investigate.

**Comment by colemonnahan** [comment]
@kellijohnson-NOAA This issue has returned with the restructuring of how the executables are packaged. The easiest thing to do here is just put empty files 'ss.dat' into the same folders as the executables. This is not an ss3sim thing but rather a known ADMB issue when using a .dat file that has a different name than the .exe. 

On the same lines, these are not very informative and could be (should be) suppressed:

````
Read 33 items
assuming version 3.30 based on first five lines of data file
````

**Comment by kellijohnson-NOAA** [comment]
I have pushed a [fix](https://github.com/kellijohnson-NOAA/r4ss/commit/1d57e1444d311367d10cd49c0d1537419dc4af78) to r4ss\development that suppresses the messages. I am guessing Ian will be in the office tomorrow and will look at my pull request then. 

I am not getting the message about `Error trying to open data input file ss.dat`. You are running ss3sim on windows right? I am guessing your error message now says ss.dat and not ss3.dat like the original issue. Thanks @colemonnahan for helping us work through these issues by the way. @k-doering-NOAA are you getting the dat warning message from ADMB?

**Comment by colemonnahan** [comment]
Yes I'm using windows. The executable is ss.exe on my installation. I dropped an empty ss.dat file in the installation folder for the R package and it solved the problem.

**Comment by k-doering-NOAA** [comment]
I also don't get the message `Error trying to open data input file ss.dat` when I use `run_ss3sim()` on Windows 10.  I am relying on the executable ss.exe within the ss3sim package.

I think this code intends to get rid of the message, right? https://github.com/ss3sim/ss3sim/blob/development/R/ss3sim_base.r#L212-L214
I wonder why this doesn't do the trick for Cole?

Thank you @colemonnahan for posting the issues you find!

**Comment by colemonnahan** [comment]
I'm in Win10; R 3.5.3 and just updated ss3sim/dev and r4ss. When I run it the error I get is this:

`Error trying to open data input file C:\Users\COLE~1.MON\RLibs\ss3sim\bin\WINDOW~1\ss.dat`

This is the same whether in parallel or serial. This is the path to the package folder binary. So writing a dummy dat file to the scenario folder is not going to work. I'm not sure why it would be different on your machine. Do you have a ss.exe file in your iteration folders after running? I do not.

**Comment by kellijohnson-NOAA** [comment]
I thought it might have been because I use devtools::load_all() to load the package rather than installing from github, but I didn't get the message after doing devtools::install_github("ss3sim/ss3sim@development") either. So my next question for you @colemonnahan is what do you get when you run
```
ss3sim::get_bin()
[1] "\"C:/Program Files/R/library/ss3sim/bin/Windows64/ss.exe\""
```

**Comment by colemonnahan** [comment]
I get this: 

"C:/Users/cole.monnahan/RLibs/ss3sim/bin/Windows64/ss.exe"

Maybe this is a terminal difference? ss3sim writes the dummy .dat into the scenario folder but calls an executable in a different folder. Maybe depending on the terminal behavior ADMB will look in the current directory vs where the .exe is? What OS are you using?

**Comment by kellijohnson-NOAA** [comment]
Windows 10 on three different computers.

**Comment by colemonnahan** [comment]
Can you check with Claudio, he's using Win10 too. When you run yours are you doing it in a temp folder? I'm running it in my own directory.

**Comment by kellijohnson-NOAA** [comment]
Claudio said he doesn't see the error either. Most of the time I am running the models in the ss3sim directory because I am lazy like that. 

I think we could just save a blank ss.dat file with each executable, but this fix would only help those installing the package from github and not those using the CRAN version because CRAN won't allow the executable folder and users have to modify their path instead.

**Comment by colemonnahan** [comment]
Up to you what to do. I wasn't aware that the binary inclusion is only working for github installs. We could totally move away from CRAN since path issues are easily the biggest issue new users run into and are annoying to help debug.

r4ss isn't on CRAN anyway

**Comment by kellijohnson-NOAA** [comment]
Ian and I both just submitted to CRAN yesterday. 

I think that I will make a new branch, once I merge master back into development, and then maybe @colemonnahan you can see if my changes make the error go away for you?

**Comment by iantaylor-NOAA** [comment]
ADMB 12.1, to be released shortly (within a few weeks?) will no longer include the error message about missing `ss.dat`. See https://github.com/admb-project/admb/issues/117 for more detail.

**Comment by kellijohnson-NOAA** [comment]
- [ ] change the executable to one compiled with admb 12.1
